import { describe, expect, it } from 'vitest'

import calendarPageSource from '../../calendar/CalendarPage.svelte?raw'
import calendarIndexSource from '$lib/calendar/index.ts?raw'
import calendarAdapterSource from '$lib/calendar/adapters/caldav-calendar-adapter.ts?raw'

describe('Calendar page source contract', () => {
  it('uses Bits UI calendar primitives with BITCH theme states instead of the placeholder panel', () => {
    expect(calendarPageSource).toContain("import { Calendar, Popover } from 'bits-ui'")
    expect(calendarPageSource).not.toContain('Accordion')
    expect(calendarPageSource).toContain("import BracketTrigger from '@/app/components/ui/BracketTrigger.svelte'")
    expect(calendarPageSource).toContain("import Dialog from '@/app/components/ui/Dialog.svelte'")
    expect(calendarPageSource).toContain("import Loader from '@/app/components/ui/Loader.svelte'")
    expect(calendarPageSource).toContain("import { menuItemClass, popoverClass } from '@/app/components/ui/styles'")
    expect(calendarPageSource).toContain('<Calendar.Root')
    expect(calendarPageSource).toContain('<Calendar.Header')
    expect(calendarPageSource).not.toContain('<Calendar.PrevButton')
    expect(calendarPageSource).not.toContain('<Calendar.NextButton')
    expect(calendarPageSource).toContain('<Calendar.Grid')
    expect(calendarPageSource).toContain('<Calendar.Day')
    expect(calendarPageSource).not.toContain('<Calendar.GridHead')
    expect(calendarPageSource).not.toContain('<Calendar.HeadCell')
    expect(calendarPageSource).toContain('{#snippet children({ weekdays })}')
    expect(calendarPageSource).toContain('ring-1 ring-primary/70')
    expect(calendarPageSource).toContain('focus-visible:outline-focus')
    expect(calendarPageSource).toContain('bg-chat-scroll/40')
    expect(calendarPageSource).toContain('calendarLabel="BITCH calendar"')
    expect(calendarPageSource).toContain("const calendarDesktopMediaQuery = '(min-width: 768px)'")
    expect(calendarPageSource).toContain('let calendarView = $state<CalendarView>(initialCalendarView())')
    expect(calendarPageSource).toContain('let calendarDesktopViewport = $state(initialCalendarDesktopViewport())')
    expect(calendarPageSource).toContain("{ id: 'month', label: 'Month' }")
    expect(calendarPageSource).toContain("{ id: 'day', label: 'Day' }")
    expect(calendarPageSource).not.toContain("{ id: 'week', label: 'Week' }")
    expect(calendarPageSource).toContain("const calendarShellClass = 'flex min-h-0 flex-1 flex-col text-ink'")
    expect(calendarPageSource).not.toContain(
      "const calendarShellClass = 'rounded-panel border border-line bg-canvas p-3 text-ink shadow-inner'"
    )
    expect(calendarPageSource).toContain('config missing')
    expect(calendarPageSource).toContain('No events returned for this date')
    expect(calendarPageSource).not.toContain("timeZone: 'UTC'")
    expect(calendarPageSource).not.toContain('Chronos panel queued')
    expect(calendarPageSource).not.toContain('fake feed')
  })

  it('loads through the public calendar facade and a dedicated CalDAV Tauri command', () => {
    expect(calendarPageSource).toContain("from '$lib/calendar'")
    expect(calendarIndexSource).toContain('./adapters/caldav-calendar-adapter')
    expect(calendarAdapterSource).toContain('get_caldav_config_status')
    expect(calendarAdapterSource).toContain('list_calendar_events')
    expect(calendarAdapterSource).toContain('sync_calendar_events')
    expect(calendarAdapterSource).toContain('calendar-sync-updated')
    expect(calendarAdapterSource).not.toContain('dashboard_request')
    expect(calendarAdapterSource).not.toContain('$lib/hermes')
  })

  it('loads cached data on initial load and syncs only from the explicit button or background event', () => {
    const handlerStart = calendarPageSource.indexOf('function handleVisibleMonthChange')
    const handlerEnd = calendarPageSource.indexOf('function selectToday', handlerStart)
    const visibleMonthHandler = calendarPageSource.slice(handlerStart, handlerEnd)
    const todayHandlerStart = calendarPageSource.indexOf('function selectToday')
    const todayHandlerEnd = calendarPageSource.indexOf('function selectCalendarView', todayHandlerStart)
    const todayHandler = calendarPageSource.slice(todayHandlerStart, todayHandlerEnd)

    expect(calendarPageSource).toContain('onMount(() => {\n    let disposed = false')
    expect(calendarPageSource).toContain('let unlisten')
    expect(calendarPageSource).toContain('loadCalendarViewRange({ background: true })')
    expect(calendarPageSource).toContain('listenCalendarSyncUpdates')
    expect(calendarPageSource).toContain('loadCalendarViewRange({ background: true })')
    expect(calendarPageSource).toContain('actions={calendarActions}')
    expect(calendarPageSource).toContain('{#snippet calendarActions()}')
    expect(calendarPageSource).not.toContain('badge={viewModel.statusLabel}')
    expect(calendarPageSource).toContain('onclick={() => void viewModel.syncNow()}')
    expect(calendarPageSource).toContain('aria-label="Sync calendar"')
    expect(calendarPageSource).toContain('title="Sync calendar"')
    expect(calendarPageSource).toContain('variant="unstyled"')
    expect(calendarPageSource).not.toContain('>Refresh</Button>')
    expect(calendarPageSource).not.toContain('onclick={() => void viewModel.refresh()}')
    expect(calendarPageSource).not.toContain('leading={selectedDateHeading}')
    expect(calendarPageSource).toContain('{activeDateLabel}</div>')
    expect(calendarPageSource).toContain('contentClass="flex min-h-0 flex-col overflow-hidden p-3"')
    expect(calendarPageSource).not.toContain('lg:grid-cols-[minmax(19rem,0.85fr)_minmax(0,1.15fr)]')
    expect(calendarPageSource).toContain('const calendarPanelActionClass = [')
    expect(calendarPageSource).toContain('const calendarViewMenuContentClass =')
    expect(calendarPageSource).toContain('const calendarViewMenuItemBaseClass =')
    expect(calendarPageSource).toContain('let calendarViewMenuOpen = $state(false)')
    expect(calendarPageSource).toContain('const calendarViewOptions = $derived.by')
    expect(calendarPageSource).toContain('calendarViews.filter(view => isCalendarViewEnabled(view.id))')
    expect(calendarPageSource).toContain('const selectedCalendarViewLabel = $derived')
    expect(calendarPageSource).toContain('function calendarViewMenuItemClass')
    expect(calendarPageSource).toContain('<Popover.Root bind:open={calendarViewMenuOpen}>')
    expect(calendarPageSource).toContain(
      'aria-label={`Choose calendar view. Current view: ${selectedCalendarViewLabel}`}'
    )
    expect(calendarPageSource).toContain('<BracketTrigger {...props} label="VIEW" value={selectedCalendarViewLabel} />')
    expect(calendarPageSource).toContain('calendar views</div>')
    expect(calendarPageSource).toContain('{#each calendarViewOptions as view (view.id)}')
    expect(calendarPageSource).toContain(
      '<button class={calendarViewMenuItemClass(view.id)} type="button" onclick={() => selectCalendarView(view.id)} aria-pressed={calendarView === view.id}>'
    )
    expect(calendarPageSource).toContain('view:{view.label.toLowerCase()}')
    expect(calendarPageSource).toContain('calendarViewMenuOpen = false')
    expect(calendarPageSource).toContain('function initialCalendarDesktopViewport')
    expect(calendarPageSource).toContain(
      "return typeof window === 'undefined' ? true : window.matchMedia(calendarDesktopMediaQuery).matches"
    )
    expect(calendarPageSource).toContain('function initialCalendarView')
    expect(calendarPageSource).toContain("return initialCalendarDesktopViewport() ? 'month' : 'day'")
    expect(calendarPageSource).toContain('function syncCalendarDesktopViewport')
    expect(calendarPageSource).toContain("if (matches || calendarView !== 'month') return")
    expect(calendarPageSource).toContain("calendarView = 'day'")
    expect(calendarPageSource).toContain('if (load) void loadCalendarViewRange({ background: true })')
    expect(calendarPageSource).toContain('function isCalendarViewEnabled')
    expect(calendarPageSource).toContain("return calendarDesktopViewport || view !== 'month'")
    expect(calendarPageSource).toContain('if (!isCalendarViewEnabled(view)) return')
    expect(calendarPageSource).toContain("if (view !== 'month') {")
    expect(calendarPageSource).toContain('agendaAnchorKey = viewModel.selectedDateKey')
    expect(calendarPageSource).toContain("selectedMonthEventUid = ''")
    expect(calendarPageSource).toContain("void scrollAgendaIntoView(viewModel.selectedDateKey, 'auto')")
    expect(calendarPageSource).toContain('const mediaQuery = window.matchMedia(calendarDesktopMediaQuery)')
    expect(calendarPageSource).toContain(
      'const handleViewportChange = (event: MediaQueryListEvent) => syncCalendarDesktopViewport(event.matches)'
    )
    expect(calendarPageSource).toContain('syncCalendarDesktopViewport(mediaQuery.matches, false)')
    expect(calendarPageSource).toContain("if (calendarView === 'month') {")
    expect(calendarPageSource).toContain("mediaQuery.addEventListener('change', handleViewportChange)")
    expect(calendarPageSource).toContain("mediaQuery.removeEventListener('change', handleViewportChange)")
    expect(calendarPageSource).not.toContain('function calendarViewButtonClass')
    expect(calendarPageSource).not.toContain('aria-label="Calendar view selector"')
    expect(calendarPageSource).not.toContain('<Button variant="unstyled" class={calendarViewButtonClass(view.id)}')
    expect(calendarPageSource).not.toContain("chrome={calendarView === view.id ? 'control' : 'ghost'}")
    expect(calendarPageSource).not.toContain("calendarView === 'week'")
    expect(calendarPageSource).not.toContain("type CalendarAgendaView = Exclude<CalendarView, 'month'>")
    expect(calendarPageSource).toContain("type CalendarView = 'day' | 'month'")
    expect(calendarPageSource).toContain('const agendaDayRowHeightPx = 360')
    expect(calendarPageSource).toContain('const agendaVirtualOverscanRows = 3')
    expect(calendarPageSource).toContain('const agendaVirtualWindowRows = 1200')
    expect(calendarPageSource).not.toContain('const agendaWeekRowHeightPx = 720')
    expect(calendarPageSource).toContain('let agendaAnchorKey = $state(viewModel.selectedDateKey)')
    expect(calendarPageSource).not.toContain('let agendaOpenRowKeys = $state<string[]>([])')
    expect(calendarPageSource).toContain('let agendaScroller = $state<HTMLElement | null>(null)')
    expect(calendarPageSource).toContain('let agendaVirtualScrollTop = $state(0)')
    expect(calendarPageSource).toContain('const agendaVirtualGrid = $derived.by<VirtualAgendaGrid>')
    expect(calendarPageSource).toContain('const virtualAgendaWindow = $derived.by<VirtualAgendaWindow>')
    expect(calendarPageSource).toContain('function scrollAgendaIntoView')
    expect(calendarPageSource).toContain('function handleAgendaScroll')
    expect(calendarPageSource).toContain('function updateSelectedAgendaFromScroll')
    expect(calendarPageSource).toContain('function createVirtualAgendaGrid')
    expect(calendarPageSource).toContain('function createVirtualAgendaWindow')
    expect(calendarPageSource).toContain('function agendaRowAtIndex')
    expect(calendarPageSource).toContain('function agendaRowIndexForDate')
    const agendaRowSnippetStart = calendarPageSource.indexOf('{#snippet agendaRow(row: VirtualAgendaRow)}')
    const agendaRowSnippetEnd = calendarPageSource.indexOf('<section class="flex h-full', agendaRowSnippetStart)
    const agendaRowSnippet = calendarPageSource.slice(agendaRowSnippetStart, agendaRowSnippetEnd)
    expect(calendarPageSource).toContain('function agendaRowKeyForDate')
    expect(calendarPageSource).toContain('function eventsForDateKeys')
    expect(calendarPageSource).toContain('const eventsByUid = new Map<string, CalendarEvent>()')
    expect(calendarPageSource).toContain('return sortCalendarEvents([...eventsByUid.values()])')
    expect(calendarPageSource).toContain('aria-label="Continuous day calendar events"')
    expect(calendarPageSource).not.toContain('Continuous week calendar events')
    expect(calendarPageSource).toContain('{#each virtualAgendaWindow.rows as row (row.key)}')
    expect(calendarPageSource).not.toContain('data-calendar-week-accordion')
    expect(calendarPageSource).not.toContain('data-calendar-agenda-accordion')
    expect(calendarPageSource).toContain('<div class="grid gap-3" data-calendar-agenda-list>')
    expect(calendarPageSource).toContain('<section class="border-b border-line/70"')
    expect(calendarPageSource).not.toContain('<Accordion.Item')
    expect(calendarPageSource).toContain('data-calendar-agenda-row={row.key}')
    expect(calendarPageSource).toContain('{@const rowEvents = eventsForDateKeys(row.dateKeys)}')
    expect(calendarPageSource).toContain('style={`min-height: ${agendaRowHeight()}px`}')
    expect(agendaRowSnippet).not.toContain('rounded-control border border-secondary/40 bg-secondary/10 px-2 py-1')
    expect(agendaRowSnippet).not.toContain('>open</span>')
    expect(calendarPageSource).toContain('{@render eventList(rowEvents)}')
    expect(calendarPageSource).toContain('{#snippet eventCard(event: CalendarEvent)}')
    expect(calendarPageSource).toContain('{@render eventCard(event)}')
    expect(calendarPageSource).not.toContain('weekDateKeys(key)')
    expect(calendarPageSource).toContain('dateKeys: [key]')
    expect(calendarPageSource).toContain('label: formatDateLabel(key)')
    expect(calendarPageSource).not.toContain('{#snippet agendaDateBlock')
    expect(calendarPageSource).not.toContain('data-calendar-event-accordion')
    expect(calendarPageSource).not.toContain('<Accordion.Content')
    expect(calendarPageSource).not.toContain('animate-accordion-up')
    expect(calendarPageSource).not.toContain('animate-accordion-down')
    expect(agendaRowSnippet).not.toContain('overflow-auto')
    expect(agendaRowSnippet).not.toContain('data-selectable="true"')
    expect(calendarPageSource).not.toContain('calendarEventsForDate(viewModel.events, dateKey)')
    expect(calendarPageSource).not.toContain('weekEventCount === 0')
    expect(calendarPageSource).not.toContain('Selected week calendar events')
    expect(calendarPageSource).toContain("calendarView === 'month'")
    expect(calendarPageSource).toContain('const initialEventMonthWindow = 6')
    expect(calendarPageSource).toContain('const eventLazyMonthStep = 24')
    expect(calendarPageSource).toContain('const maxProgrammaticScrollDurationMs = 360')
    expect(calendarPageSource).toContain('const minProgrammaticScrollDurationMs = 120')
    expect(calendarPageSource).toContain('const monthEventLoaderSlotHeightPx = 28')
    expect(calendarPageSource).toContain('const monthVirtualMonthWindow = 1200')
    expect(calendarPageSource).toContain('const monthVirtualOverscanRows = 6')
    expect(calendarPageSource).toContain('const monthWeekRowHeightPx = 112')
    expect(calendarPageSource).not.toContain('let cachedMonthsBefore = $state(0)')
    expect(calendarPageSource).not.toContain('let cachedMonthsAfter = $state(0)')
    expect(calendarPageSource).toContain('let initialCalendarLoading = $state(true)')
    expect(calendarPageSource).toContain('let eventMonthsBefore = $state(initialEventMonthWindow)')
    expect(calendarPageSource).toContain('let eventMonthsAfter = $state(initialEventMonthWindow)')
    expect(calendarPageSource).toContain('let monthVirtualScrollTop = $state(0)')
    expect(calendarPageSource).toContain('let monthViewportHeight = $state(monthWeekRowHeightPx * 6)')
    expect(calendarPageSource).toContain("let programmaticAgendaScrollTargetKey = ''")
    expect(calendarPageSource).toContain('const eventRangeOptions = $derived.by<CalendarVisibleRangeOptions>')
    expect(calendarPageSource).toContain('monthsBefore: eventMonthsBefore')
    expect(calendarPageSource).toContain('monthsAfter: eventMonthsAfter')
    expect(calendarPageSource).toContain('function loadCalendarRange')
    expect(calendarPageSource).toContain('function monthRangeOptions')
    expect(calendarPageSource).toContain('function activeRangeOptions')
    expect(calendarPageSource).toContain('return eventRangeOptions')
    expect(calendarPageSource).not.toContain('const loadedMonthCount = $derived')
    expect(calendarPageSource).toContain('numberOfMonths={1}')
    expect(calendarPageSource).toContain('{#if initialCalendarLoading && viewModel.configStatus === null}')
    expect(calendarPageSource).toContain('<Loader size="lg" label="Loading calendar" />')
    expect(calendarPageSource).not.toContain('Loading calendar events…')
    expect(calendarPageSource).toContain('aria-label="Continuous month calendar"')
    expect(calendarPageSource).toContain('const calendarWeekdayHeaderClass =')
    expect(calendarPageSource).toContain('sticky top-0 z-[1] grid grid-cols-7')
    expect(calendarPageSource).toContain('const calendarWeekdayCellClass =')
    expect(calendarPageSource).toContain('{day.toLowerCase()}</div>')
    expect(calendarPageSource).toContain('overflow-y-auto')
    expect(calendarPageSource).not.toContain('space-y-8')
    expect(calendarPageSource).toContain('const monthVirtualGrid = $derived.by<VirtualMonthGrid>')
    expect(calendarPageSource).toContain(
      'createVirtualMonthGrid(visibleMonth.toString(), monthVirtualMonthWindow, monthVirtualMonthWindow)'
    )
    expect(calendarPageSource).toContain('const virtualWeekWindow = $derived.by<VirtualWeekWindow>')
    expect(calendarPageSource).toContain(
      'createVirtualWeekWindow(monthVirtualGrid, monthVirtualScrollTop, monthViewportHeight)'
    )
    expect(calendarPageSource).toContain('const monthEventsByDate = $derived.by<Map<string, CalendarEvent[]>>')
    expect(calendarPageSource).toContain('monthEventMap(viewModel.events)')
    expect(calendarPageSource).toContain('function monthEventMap')
    expect(calendarPageSource).toContain('calendarEventOverlapsDate(event, dateKey)')
    expect(calendarPageSource).toContain('sortCalendarEvents(dateEvents)')
    expect(calendarPageSource).toContain('return monthEventsByDate.get(dateKey) ?? []')
    expect(calendarPageSource).not.toContain('function continuousMonthWeeks')
    expect(calendarPageSource).toContain('function createVirtualMonthGrid')
    expect(calendarPageSource).toContain('function createVirtualWeekWindow')
    expect(calendarPageSource).toContain('function monthWeekAtIndex')
    expect(calendarPageSource).toContain('function monthWeekFromStartDate')
    expect(calendarPageSource).toContain('function dominantMonthKey')
    expect(calendarPageSource).toContain("cell.dateKey.endsWith('-01')")
    expect(calendarPageSource).toContain('if (firstOfMonth) return monthStartKey(firstOfMonth.dateKey)')
    expect(calendarPageSource).toContain('function monthDayClass')
    expect(calendarPageSource).toContain("'border-primary/30 bg-primary/15 hover:bg-primary/20'")
    expect(calendarPageSource).toContain("'border-transparent bg-canvas/30 hover:bg-primary/10'")
    expect(calendarPageSource).toContain('function monthDayLabelClass')
    expect(calendarPageSource).not.toContain('function isCachedMonth')
    expect(calendarPageSource).not.toContain('function isLoadingHighlightedMonthCell')
    expect(calendarPageSource).not.toContain('return isCurrentMonthCell(dateKey) && !isCachedMonth(dateKey)')
    expect(calendarPageSource).toContain("isCurrentMonthCell(dateKey) ? 'text-ink-bright' : 'text-ink-muted/35'")
    expect(calendarPageSource).toContain('function monthEventButtonClass')
    expect(calendarPageSource).toContain(
      "selectedMonthEventUid === eventUid ? 'bg-primary/15 text-ink-bright ring-1 ring-primary/40'"
    )
    expect(calendarPageSource).toContain('function monthEventRowClass')
    expect(calendarPageSource).toContain('function monthEventTitleClass')
    expect(calendarPageSource).toContain('function monthEventTimeClass')
    expect(calendarPageSource).toContain('function monthEventMoreClass')
    expect(calendarPageSource).not.toContain('{#each continuousWeeks as week')
    expect(calendarPageSource).toContain('{#each virtualWeekWindow.rows as row (row.startKey)}')
    expect(calendarPageSource).toContain('virtualWeekWindow.topSpacerHeight')
    expect(calendarPageSource).toContain('virtualWeekWindow.bottomSpacerHeight')
    expect(calendarPageSource).toContain('data-calendar-week-month={row.monthKey}')
    expect(calendarPageSource).toContain('data-calendar-week-start={row.startKey}')
    expect(calendarPageSource).toContain('{#each row.week as cell (cell.dateKey)}')
    expect(calendarPageSource).toContain('month={cell.month}')
    expect(calendarPageSource).toContain('{@const cellEvents = eventsForDateKey(cell.dateKey)}')
    expect(calendarPageSource).toContain('cellEvents.slice(0, 4)')
    expect(calendarPageSource).toContain('class={monthEventRowClass()}')
    expect(calendarPageSource).toContain('class={monthEventTitleClass()}')
    expect(calendarPageSource).toContain('class={monthEventTimeClass()}')
    expect(calendarPageSource).toContain('class={monthEventMoreClass()}')
    expect(calendarPageSource).toContain('variant="unstyled"')
    expect(calendarPageSource).toContain('class={monthEventButtonClass(event.uid)}')
    expect(calendarPageSource).toContain('onclick={clickEvent => selectMonthEvent(clickEvent, event, cell.dateKey)}')
    expect(calendarPageSource).toContain('aria-label={`Show details for ${event.title}`}')
    expect(calendarPageSource).not.toContain('class={monthEventRowClass(cell.dateKey)}')
    expect(calendarPageSource).not.toContain('events: eventsForDateKey(dateKey)')
    expect(calendarPageSource).not.toContain('cell.events')
    expect(calendarPageSource).toContain('+{cellEvents.length - 4} more')
    expect(calendarPageSource).toContain('onclick={selectToday}')
    expect(calendarPageSource).toContain("{#if calendarView !== 'month'}")
    expect(calendarPageSource).toContain(
      '<Button variant="unstyled" class={`${calendarPanelActionClass} text-secondary`} onclick={selectToday}>Today</Button>'
    )
    expect(calendarPageSource).toContain('<Button size="sm" variant="secondary" onclick={selectToday}>Today</Button>')
    expect(todayHandler).toContain("if (calendarView === 'month')")
    expect(todayHandler).toContain("void scrollMonthIntoView(todayKey, 'smooth')")
    expect(todayHandler).toContain('agendaAnchorKey = todayKey')
    expect(todayHandler).toContain("void scrollAgendaIntoView(todayKey, 'smooth')")
    expect(todayHandler.indexOf("if (calendarView === 'month')")).toBeLessThan(
      todayHandler.indexOf('void loadCalendarViewRange({ background: true })')
    )
    expect(todayHandler).not.toContain('resetLazyMonthWindow()')
    expect(calendarPageSource).toContain('function navigateVisibleMonth')
    expect(calendarPageSource).toContain('const calendarHeaderTitleClass =')
    expect(calendarPageSource).toContain('const calendarHeaderControlsClass =')
    expect(calendarPageSource).toContain('<Calendar.Header class={calendarHeaderClass}>')
    expect(calendarPageSource).toContain('<div class={calendarHeaderTitleClass}>{currentMonthInViewLabel}</div>')
    expect(calendarPageSource).toContain('<div class={calendarHeaderControlsClass} aria-label="Month navigation">')
    expect(calendarPageSource).toContain(
      '<Button size="icon" aria-label="Previous month" onclick={() => navigateVisibleMonth(-1)}>‹</Button>'
    )
    expect(calendarPageSource).toContain(
      '<Button size="icon" aria-label="Next month" onclick={() => navigateVisibleMonth(1)}>›</Button>'
    )
    expect(calendarPageSource).not.toContain('const calendarNavClass =')
    expect(calendarPageSource).not.toContain('class={calendarNavClass}')
    expect(calendarPageSource).toContain('let currentMonthInViewKey = $state(viewModel.visibleAnchorKey)')
    expect(calendarPageSource).toContain('let monthScroller = $state<HTMLElement | null>(null)')
    expect(calendarPageSource).toContain('let monthScrollAnimationFrame: null | number = null')
    expect(calendarPageSource).toContain("let programmaticMonthScrollTargetKey = ''")
    expect(calendarPageSource).toContain('let programmaticMonthScrollEndTimer: null | number = null')
    expect(calendarPageSource).toContain("let selectedMonthEventUid = $state('')")
    expect(calendarPageSource).toContain("let selectedAgendaEventUid = $state('')")
    expect(calendarPageSource).toContain('let eventDetailDialogOpen = $state(false)')
    expect(calendarPageSource).toContain('const selectedMonthEvent = $derived.by<CalendarEvent | null>')
    expect(calendarPageSource).toContain('const selectedAgendaEvent = $derived.by<CalendarEvent | null>')
    expect(calendarPageSource).toContain(
      'const currentMonthInViewLabel = $derived(formatMonthHeading(currentMonthInViewKey || visibleMonth.toString()))'
    )
    expect(calendarPageSource).toContain('function handleMonthScroll()')
    expect(calendarPageSource).toContain('monthScrollFrame = window.requestAnimationFrame')
    expect(calendarPageSource).toContain('function updateHighlightedMonthFromScroll')
    expect(calendarPageSource).not.toContain("querySelectorAll<HTMLElement>('[data-calendar-week-month]')")
    expect(calendarPageSource).not.toContain("row.querySelectorAll<HTMLElement>('[data-calendar-day-month]')")
    expect(calendarPageSource).toContain('function highlightedMonthKey')
    expect(calendarPageSource).toContain('function monthGridScrollTop')
    expect(calendarPageSource).toContain('function monthWeekRowHeight')
    expect(calendarPageSource).toContain('const firstFullVisibleIndex = clamp(')
    expect(calendarPageSource).toContain(
      'Math.ceil((monthGridScrollTop(scroller) - monthFullRowVisibilityEpsilonPx) / rowHeight)'
    )
    expect(calendarPageSource).toContain(
      'return dominantMonthKey(monthWeekAtIndex(monthVirtualGrid, firstFullVisibleIndex))'
    )
    expect(calendarPageSource).toContain('function monthWeekAtIndex(grid: VirtualMonthGrid, index: number): MonthWeek')
    expect(calendarPageSource).toContain('function dominantMonthKey(week: MonthWeek): string')
    expect(calendarPageSource).toContain("const firstOfMonth = week.find(cell => cell.dateKey.endsWith('-01'))")
    expect(calendarPageSource).toContain('right[1] - left[1] || left[0].localeCompare(right[0])')
    expect(calendarPageSource).toContain('data-calendar-day-month={monthStartKey(cell.dateKey)}')
    expect(calendarPageSource).toContain('data-calendar-weekday-header')
    expect(calendarPageSource).not.toContain('function highlightedMonthRow')
    expect(calendarPageSource).not.toContain('return visibleRows[1] ?? visibleRows[0]')
    expect(calendarPageSource).toContain('function selectMonthEvent')
    expect(calendarPageSource).toContain('clickEvent.stopPropagation()')
    expect(calendarPageSource).toContain('selectedMonthEventUid = calendarEvent.uid')
    expect(calendarPageSource).toContain('function openAgendaEventDetail')
    expect(calendarPageSource).toContain('selectedAgendaEventUid = calendarEvent.uid')
    expect(calendarPageSource).toContain('if (!calendarDesktopViewport) eventDetailDialogOpen = true')
    expect(calendarPageSource).toContain('function closeMonthEventDetail')
    expect(calendarPageSource).toContain('function closeAgendaEventDetail')
    expect(calendarPageSource).toContain('function closeEventDetail')
    expect(calendarPageSource).toContain("selectedMonthEventUid = ''")
    expect(calendarPageSource).toContain("selectedAgendaEventUid = ''")
    expect(calendarPageSource).toContain('function scrollMonthIntoView')
    expect(calendarPageSource).toContain('function scrollMonthScroller')
    expect(calendarPageSource).toContain('const duration = Math.min(')
    expect(calendarPageSource).toContain('const eased = 1 - Math.pow(1 - progress, 3)')
    expect(calendarPageSource).toContain('monthScrollAnimationFrame = window.requestAnimationFrame(step)')
    expect(calendarPageSource).toContain('function beginProgrammaticMonthScroll')
    expect(calendarPageSource).toContain('function scheduleProgrammaticMonthScrollEnd')
    expect(calendarPageSource).toContain('if (programmaticMonthScrollTargetKey)')
    expect(calendarPageSource).toContain('currentMonthInViewKey = programmaticMonthScrollTargetKey')
    expect(calendarPageSource).toContain('function monthScrollTopForMonth')
    expect(calendarPageSource).toContain('function monthWeekIndex')
    expect(calendarPageSource).toContain('await tick()')
    expect(calendarPageSource).toContain(
      'scrollMonthScroller(scroller, monthScrollTopForMonth(targetMonthKey), targetMonthKey, behavior)'
    )
    expect(calendarPageSource).not.toContain('scroller.scrollTo({')
    expect(calendarPageSource).not.toContain('function ensureRenderedMonth')
    expect(calendarPageSource).not.toContain('await ensureRenderedMonth(targetMonthKey)')
    expect(calendarPageSource).not.toContain('const rendered = await ensureRenderedMonth(targetMonthKey)')
    expect(calendarPageSource).not.toContain('if (!rendered) return')
    expect(calendarPageSource).toContain('function maybeLoadEventsForMonth')
    expect(calendarPageSource).toContain(
      "extendEventRange('before', Math.max(eventMonthsBefore + eventLazyMonthStep, Math.abs(offset) + initialEventMonthWindow))"
    )
    expect(calendarPageSource).toContain(
      "extendEventRange('after', Math.max(eventMonthsAfter + eventLazyMonthStep, offset + initialEventMonthWindow))"
    )
    expect(calendarPageSource).toContain('function extendEventRange')
    expect(calendarPageSource).toContain(
      'void loadCalendarRange(monthRangeOptions(nextMonthsBefore, nextMonthsAfter), { background: true }).finally(() => {'
    )
    expect(calendarPageSource).not.toContain('if (!loaded) return false')
    expect(calendarPageSource).toContain('eventMonthsBefore = nextMonthsBefore')
    expect(calendarPageSource).toContain('eventMonthsAfter = nextMonthsAfter')
    expect(calendarPageSource).not.toContain('restoreMonthScrollAnchor(scroller, scrollAnchor)')
    expect(calendarPageSource).not.toContain('scroller.scrollTop += scroller.scrollHeight - previousScrollHeight')
    expect(calendarPageSource).toContain('<Loader size="md" label="Loading previous calendar events" />')
    expect(calendarPageSource).toContain('<Loader size="md" label="Loading next calendar events" />')
    expect(calendarPageSource).not.toContain('<Loader size="sm" label="Loading calendar month" />')
    expect(calendarPageSource).not.toContain('sticky top-8')
    expect(calendarPageSource).not.toContain('sticky bottom-0')
    expect(calendarPageSource).not.toContain('function resetMonthScrollerToTop()')
    expect(calendarPageSource).not.toContain('monthScroller.scrollTop = 0')
    expect(calendarPageSource).toContain('bind:this={monthScroller} onscroll={handleMonthScroll}')
    expect(calendarPageSource).toContain('data-calendar-week-month={row.monthKey}')
    expect(calendarPageSource).not.toContain('data-calendar-month={month.value.toString()}')
    expect(calendarPageSource).not.toContain(
      '<h2 class="font-hud text-base font-bold uppercase tracking-[0.12em] text-ink-bright">'
    )
    expect(calendarPageSource).toContain('{currentMonthInViewLabel}</div>')
    expect(calendarPageSource).toContain('const monthLayoutClass =')
    expect(calendarPageSource).toContain('const agendaLayoutClass =')
    expect(calendarPageSource).toContain('grid-cols-[minmax(0,1fr)_minmax(18rem,24rem)]')
    expect(calendarPageSource).toContain('md:grid-cols-[minmax(0,1fr)_minmax(18rem,24rem)]')
    expect(calendarPageSource).not.toContain('xl:grid-cols-[minmax(0,1fr)_minmax(18rem,24rem)]')
    const eventCardSnippetStart = calendarPageSource.indexOf('{#snippet eventCard(event: CalendarEvent)}')
    const eventCardSnippetEnd = calendarPageSource.indexOf('{#snippet eventList', eventCardSnippetStart)
    const eventCardSnippet = calendarPageSource.slice(eventCardSnippetStart, eventCardSnippetEnd)
    const detailLeadingStart = calendarPageSource.indexOf('{#snippet eventDetailLeading()}')
    const detailLeadingEnd = calendarPageSource.indexOf('{#snippet linkedText', detailLeadingStart)
    const detailLeading = calendarPageSource.slice(detailLeadingStart, detailLeadingEnd)
    expect(calendarPageSource).toContain('{#snippet eventDetailLeading()}')
    expect(detailLeading).toContain('aria-label="Close event detail"')
    expect(detailLeading).toContain('title="Close event detail"')
    expect(detailLeading).toContain('>\n    x\n  </Button>')
    expect(calendarPageSource).not.toContain('{#snippet monthEventDetailActions()}')
    expect(calendarPageSource).not.toContain('actions={monthEventDetailActions}')
    expect(calendarPageSource).not.toContain('onclick={closeMonthEventDetail}>Close</Button>')
    expect(calendarPageSource).toContain('{#snippet eventDetail(event: CalendarEvent)}')
    expect(calendarPageSource).toContain('aria-label={`Details for ${event.title}`}')
    expect(calendarPageSource).toContain('leading={eventDetailLeading}')
    expect(calendarPageSource).toContain('{#if selectedMonthEvent}')
    expect(calendarPageSource).toContain('title="EVENT DETAIL"')
    const monthBranchStart = calendarPageSource.indexOf("{#if calendarView === 'month'}")
    const calendarPanelStart = calendarPageSource.indexOf('<Panel title="CALENDAR"', monthBranchStart)
    const calendarPanelEnd = calendarPageSource.indexOf('</Panel>', calendarPanelStart)
    const detailPanelStart = calendarPageSource.indexOf('title="EVENT DETAIL"', calendarPanelEnd)
    expect(detailPanelStart).toBeGreaterThan(calendarPanelEnd)
    expect(calendarPanelEnd).toBeGreaterThan(calendarPanelStart)
    expect(calendarPageSource).not.toContain('badge={formatCalendarEventTime(selectedMonthEvent)}')
    expect(calendarPageSource).toContain('{@render eventDetail(selectedMonthEvent)}')
    expect(calendarPageSource).toContain('{@render eventDetail(selectedAgendaEvent)}')
    expect(calendarPageSource).toContain('<div class={agendaLayoutClass}>')
    expect(calendarPageSource).toContain('class="hidden min-h-0 md:flex"')
    expect(calendarPageSource).toContain('<Dialog\n    bind:open={eventDetailDialogOpen}')
    expect(calendarPageSource).toContain(
      'description={selectedAgendaEventDialogDescription || selectedAgendaEvent.title}'
    )
    expect(calendarPageSource).toContain('class="w-[min(38rem,calc(100vw-2rem))] md:hidden"')
    expect(calendarPageSource).not.toContain('{@render eventCard(selectedMonthEvent)}')
    expect(calendarPageSource).not.toContain('{formatMonthHeading(visibleMonth.toString())}</div>')
    expect(calendarPageSource).not.toContain('<Calendar.Heading')
    expect(calendarPageSource).toContain('const eventCardClass = [')
    expect(calendarPageSource).toContain(
      'block w-full !border !border-solid border-line bg-surface-raised p-3 text-left transition'
    )
    expect(calendarPageSource).not.toContain(
      'w-full rounded-panel border border-line bg-surface-raised p-3 text-left transition'
    )
    expect(calendarPageSource).toContain('hover:border-line-strong hover:bg-canvas/75')
    expect(calendarPageSource).toContain('function eventCardButtonClass')
    expect(eventCardSnippet).toContain('<Button')
    expect(eventCardSnippet).toContain('variant="unstyled"')
    expect(eventCardSnippet).toContain('class={eventCardButtonClass(event.uid)}')
    expect(eventCardSnippet).toContain('onclick={() => openAgendaEventDetail(event)}')
    expect(eventCardSnippet).toContain('aria-pressed={selectedAgendaEventUid === event.uid}')
    expect(eventCardSnippet).not.toContain('<article class={eventCardClass}>')
    expect(eventCardSnippet).toContain('grid grid-cols-[minmax(0,1fr)_minmax(6.5rem,9rem)] items-start gap-3')
    expect(calendarPageSource).toContain(
      'w-full justify-self-end rounded-control border border-line bg-canvas px-2 py-1 text-right font-mono text-xs tabular-nums text-secondary'
    )
    expect(calendarPageSource).toContain('{formatCalendarEventTime(event)}')
    expect(calendarPageSource).not.toContain('flex flex-wrap gap-1.5 md:justify-end')
    expect(eventCardSnippet).not.toContain(
      'mt-3 flex items-center justify-between gap-3 border-t border-line/60 pt-2 font-mono text-[0.62rem] text-ink-faint'
    )
    expect(eventCardSnippet).not.toContain('{@render linkedText(eventDescription(event))}')
    expect(calendarPageSource).toContain('whitespace-pre-wrap wrap-break-word')
    expect(calendarPageSource).toContain('type LinkedTextSegment')
    expect(calendarPageSource).toContain('function linkedTextSegments')
    expect(calendarPageSource).toContain('border-l border-line/70 pl-2')
    expect(calendarPageSource).toContain('{@render linkedText(event.location)}')
    expect(calendarPageSource).toContain('{@render linkedText(eventDescription(event))}')
    expect(calendarPageSource.indexOf('{@render linkedText(event.location)}')).toBeLessThan(
      calendarPageSource.indexOf('{@render linkedText(eventDescription(event))}')
    )
    expect(calendarPageSource).toContain('href={segment.href} target="_blank" rel="noreferrer"')
    expect(calendarPageSource).not.toContain('<span class="break-all"> · {event.location}</span>')
    expect(calendarPageSource).not.toContain('${eventPillClass} max-w-full truncate')
    expect(calendarPageSource).not.toContain('title={event.location}>{event.location}</span>')
    expect(calendarPageSource).not.toContain('title={event.uid}>{event.uid}</span>')
    expect(calendarPageSource).not.toContain('line-clamp-3')
    expect(calendarPageSource).not.toContain('title="DAY FEED"')
    expect(calendarPageSource).not.toContain('badge={selectedEvents.length')
    expect(calendarPageSource).not.toContain('No calendar collection configured')
    expect(calendarPageSource).not.toContain('viewModel.configStatus?.calendarUrl')
    expect(calendarPageSource).not.toContain('viewModel.configStatus?.username')
    expect(visibleMonthHandler).toContain('visibleMonth = value')
    expect(visibleMonthHandler).toContain('currentMonthInViewKey = monthStartKey(value.toString())')
    expect(visibleMonthHandler).toContain('viewModel.setVisibleAnchor(value.toString())')
    expect(visibleMonthHandler).toContain("void scrollMonthIntoView(value.toString(), 'auto')")
    expect(visibleMonthHandler).not.toContain('loadCalendarViewRange')
    expect(visibleMonthHandler).not.toContain('viewModel.loadVisibleRange')
    expect(visibleMonthHandler).not.toContain('viewModel.refresh')
    expect(visibleMonthHandler).not.toContain('viewModel.syncNow')
  })
})
