import { describe, expect, it } from 'vitest'

import calendarPageSource from '../../calendar/CalendarPage.svelte?raw'
import calendarIndexSource from '$lib/calendar/index.ts?raw'
import calendarAdapterSource from '$lib/calendar/adapters/caldav-calendar-adapter.ts?raw'

describe('Calendar page source contract', () => {
  it('uses Bits UI calendar primitives with BITCH theme states instead of the placeholder panel', () => {
    expect(calendarPageSource).toContain("import { Calendar } from 'bits-ui'")
    expect(calendarPageSource).toContain("import Loader from '@/app/components/ui/Loader.svelte'")
    expect(calendarPageSource).toContain('<Calendar.Root')
    expect(calendarPageSource).toContain('<Calendar.Header')
    expect(calendarPageSource).not.toContain('<Calendar.PrevButton')
    expect(calendarPageSource).not.toContain('<Calendar.NextButton')
    expect(calendarPageSource).toContain('<Calendar.Grid')
    expect(calendarPageSource).toContain('<Calendar.Day')
    expect(calendarPageSource).not.toContain('<Calendar.GridHead')
    expect(calendarPageSource).not.toContain('<Calendar.HeadCell')
    expect(calendarPageSource).toContain('{#snippet children({ weekdays })}')
    expect(calendarPageSource).toContain('ring-1 ring-primary/70')
    expect(calendarPageSource).toContain('focus-visible:outline-focus')
    expect(calendarPageSource).toContain('bg-chat-scroll/40')
    expect(calendarPageSource).toContain('calendarLabel="BITCH calendar"')
    expect(calendarPageSource).toContain("let calendarView = $state<CalendarView>('month')")
    expect(calendarPageSource).toContain("{ id: 'month', label: 'Month' }")
    expect(calendarPageSource).toContain("{ id: 'day', label: 'Day' }")
    expect(calendarPageSource).toContain("{ id: 'week', label: 'Week' }")
    expect(calendarPageSource).toContain("const calendarShellClass = 'flex min-h-0 flex-1 flex-col text-ink'")
    expect(calendarPageSource).not.toContain(
      "const calendarShellClass = 'rounded-panel border border-line bg-canvas p-3 text-ink shadow-inner'"
    )
    expect(calendarPageSource).toContain('config missing')
    expect(calendarPageSource).toContain('No events returned for this date')
    expect(calendarPageSource).not.toContain("timeZone: 'UTC'")
    expect(calendarPageSource).not.toContain('Chronos panel queued')
    expect(calendarPageSource).not.toContain('fake feed')
  })

  it('loads through the public calendar facade and a dedicated CalDAV Tauri command', () => {
    expect(calendarPageSource).toContain("from '$lib/calendar'")
    expect(calendarIndexSource).toContain('./adapters/caldav-calendar-adapter')
    expect(calendarAdapterSource).toContain('get_caldav_config_status')
    expect(calendarAdapterSource).toContain('list_calendar_events')
    expect(calendarAdapterSource).toContain('sync_calendar_events')
    expect(calendarAdapterSource).toContain('calendar-sync-updated')
    expect(calendarAdapterSource).not.toContain('dashboard_request')
    expect(calendarAdapterSource).not.toContain('$lib/hermes')
  })

  it('loads cached data on initial load and syncs only from the explicit button or background event', () => {
    const handlerStart = calendarPageSource.indexOf('function handleVisibleMonthChange')
    const handlerEnd = calendarPageSource.indexOf('function selectToday', handlerStart)
    const visibleMonthHandler = calendarPageSource.slice(handlerStart, handlerEnd)
    const todayHandlerStart = calendarPageSource.indexOf('function selectToday')
    const todayHandlerEnd = calendarPageSource.indexOf('function selectCalendarView', todayHandlerStart)
    const todayHandler = calendarPageSource.slice(todayHandlerStart, todayHandlerEnd)

    expect(calendarPageSource).toContain('onMount(() => {\n    let disposed = false')
    expect(calendarPageSource).toContain('let unlisten')
    expect(calendarPageSource).toContain('loadCalendarViewRange({ background: true })')
    expect(calendarPageSource).toContain('listenCalendarSyncUpdates')
    expect(calendarPageSource).toContain('loadCalendarViewRange({ background: true })')
    expect(calendarPageSource).toContain('actions={calendarActions}')
    expect(calendarPageSource).toContain('{#snippet calendarActions()}')
    expect(calendarPageSource).not.toContain('badge={viewModel.statusLabel}')
    expect(calendarPageSource).toContain('onclick={() => void viewModel.syncNow()}')
    expect(calendarPageSource).toContain('aria-label="Sync calendar"')
    expect(calendarPageSource).toContain('title="Sync calendar"')
    expect(calendarPageSource).toContain('variant="unstyled"')
    expect(calendarPageSource).not.toContain('>Refresh</Button>')
    expect(calendarPageSource).not.toContain('onclick={() => void viewModel.refresh()}')
    expect(calendarPageSource).not.toContain('leading={selectedDateHeading}')
    expect(calendarPageSource).toContain('{activeDateLabel}</div>')
    expect(calendarPageSource).toContain('contentClass="flex min-h-0 flex-col overflow-hidden p-3"')
    expect(calendarPageSource).not.toContain('lg:grid-cols-[minmax(19rem,0.85fr)_minmax(0,1.15fr)]')
    expect(calendarPageSource).toContain('const calendarPanelActionClass = [')
    expect(calendarPageSource).toContain('function calendarViewButtonClass')
    expect(calendarPageSource).toContain('aria-label="Calendar view selector"')
    expect(calendarPageSource).toContain('<Button variant="unstyled" class={calendarViewButtonClass(view.id)}')
    expect(calendarPageSource).toContain('onclick={() => selectCalendarView(view.id)}')
    expect(calendarPageSource).not.toContain("chrome={calendarView === view.id ? 'control' : 'ghost'}")
    expect(calendarPageSource).toContain("calendarView === 'week'")
    expect(calendarPageSource).toContain('weekDateKeys(viewModel.selectedDateKey)')
    expect(calendarPageSource).toContain('calendarEventsForDate(viewModel.events, dateKey)')
    expect(calendarPageSource).toContain('weekEventCount === 0')
    expect(calendarPageSource).toContain('Selected week calendar events')
    expect(calendarPageSource).toContain("calendarView === 'month'")
    expect(calendarPageSource).toContain('const initialEventMonthWindow = 6')
    expect(calendarPageSource).toContain('const eventLazyMonthStep = 24')
    expect(calendarPageSource).toContain('const maxProgrammaticScrollDurationMs = 360')
    expect(calendarPageSource).toContain('const minProgrammaticScrollDurationMs = 120')
    expect(calendarPageSource).toContain('const monthEventLoaderSlotHeightPx = 28')
    expect(calendarPageSource).toContain('const monthVirtualMonthWindow = 1200')
    expect(calendarPageSource).toContain('const monthVirtualOverscanRows = 6')
    expect(calendarPageSource).toContain('const monthWeekRowHeightPx = 112')
    expect(calendarPageSource).not.toContain('let cachedMonthsBefore = $state(0)')
    expect(calendarPageSource).not.toContain('let cachedMonthsAfter = $state(0)')
    expect(calendarPageSource).toContain('let initialCalendarLoading = $state(true)')
    expect(calendarPageSource).toContain('let eventMonthsBefore = $state(initialEventMonthWindow)')
    expect(calendarPageSource).toContain('let eventMonthsAfter = $state(initialEventMonthWindow)')
    expect(calendarPageSource).toContain('let monthVirtualScrollTop = $state(0)')
    expect(calendarPageSource).toContain('let monthViewportHeight = $state(monthWeekRowHeightPx * 6)')
    expect(calendarPageSource).toContain('const eventRangeOptions = $derived.by<CalendarVisibleRangeOptions>')
    expect(calendarPageSource).toContain('monthsBefore: eventMonthsBefore')
    expect(calendarPageSource).toContain('monthsAfter: eventMonthsAfter')
    expect(calendarPageSource).toContain('function loadCalendarRange')
    expect(calendarPageSource).toContain('function monthRangeOptions')
    expect(calendarPageSource).not.toContain('const loadedMonthCount = $derived')
    expect(calendarPageSource).toContain('numberOfMonths={1}')
    expect(calendarPageSource).toContain('{#if initialCalendarLoading && viewModel.configStatus === null}')
    expect(calendarPageSource).toContain('<Loader size="xl" label="Loading calendar" />')
    expect(calendarPageSource).not.toContain('Loading calendar events…')
    expect(calendarPageSource).toContain('aria-label="Continuous month calendar"')
    expect(calendarPageSource).toContain('const calendarWeekdayHeaderClass =')
    expect(calendarPageSource).toContain('sticky top-0 z-20 grid grid-cols-7')
    expect(calendarPageSource).toContain('const calendarWeekdayCellClass =')
    expect(calendarPageSource).toContain('{day.toLowerCase()}</div>')
    expect(calendarPageSource).toContain('overflow-y-auto')
    expect(calendarPageSource).not.toContain('space-y-8')
    expect(calendarPageSource).toContain('const monthVirtualGrid = $derived.by<VirtualMonthGrid>')
    expect(calendarPageSource).toContain(
      'createVirtualMonthGrid(visibleMonth.toString(), monthVirtualMonthWindow, monthVirtualMonthWindow)'
    )
    expect(calendarPageSource).toContain('const virtualWeekWindow = $derived.by<VirtualWeekWindow>')
    expect(calendarPageSource).toContain(
      'createVirtualWeekWindow(monthVirtualGrid, monthVirtualScrollTop, monthViewportHeight)'
    )
    expect(calendarPageSource).toContain('const monthEventsByDate = $derived.by<Map<string, CalendarEvent[]>>')
    expect(calendarPageSource).toContain('monthEventMap(viewModel.events)')
    expect(calendarPageSource).toContain('function monthEventMap')
    expect(calendarPageSource).toContain('calendarEventOverlapsDate(event, dateKey)')
    expect(calendarPageSource).toContain('sortCalendarEvents(dateEvents)')
    expect(calendarPageSource).toContain('return monthEventsByDate.get(dateKey) ?? []')
    expect(calendarPageSource).not.toContain('function continuousMonthWeeks')
    expect(calendarPageSource).toContain('function createVirtualMonthGrid')
    expect(calendarPageSource).toContain('function createVirtualWeekWindow')
    expect(calendarPageSource).toContain('function monthWeekAtIndex')
    expect(calendarPageSource).toContain('function monthWeekFromStartDate')
    expect(calendarPageSource).toContain('function dominantMonthKey')
    expect(calendarPageSource).toContain("cell.dateKey.endsWith('-01')")
    expect(calendarPageSource).toContain('if (firstOfMonth) return monthStartKey(firstOfMonth.dateKey)')
    expect(calendarPageSource).toContain('function monthDayClass')
    expect(calendarPageSource).toContain("'border-primary/30 bg-primary/15 hover:bg-primary/20'")
    expect(calendarPageSource).toContain("'border-transparent bg-canvas/30 hover:bg-primary/10'")
    expect(calendarPageSource).toContain('function monthDayLabelClass')
    expect(calendarPageSource).not.toContain('function isCachedMonth')
    expect(calendarPageSource).not.toContain('function isLoadingHighlightedMonthCell')
    expect(calendarPageSource).not.toContain('return isCurrentMonthCell(dateKey) && !isCachedMonth(dateKey)')
    expect(calendarPageSource).toContain("isCurrentMonthCell(dateKey) ? 'text-ink-bright' : 'text-ink-muted/35'")
    expect(calendarPageSource).toContain('function monthEventRowClass')
    expect(calendarPageSource).toContain('function monthEventTitleClass')
    expect(calendarPageSource).toContain('function monthEventTimeClass')
    expect(calendarPageSource).toContain('function monthEventMoreClass')
    expect(calendarPageSource).not.toContain('{#each continuousWeeks as week')
    expect(calendarPageSource).toContain('{#each virtualWeekWindow.rows as row (row.startKey)}')
    expect(calendarPageSource).toContain('virtualWeekWindow.topSpacerHeight')
    expect(calendarPageSource).toContain('virtualWeekWindow.bottomSpacerHeight')
    expect(calendarPageSource).toContain('data-calendar-week-month={row.monthKey}')
    expect(calendarPageSource).toContain('data-calendar-week-start={row.startKey}')
    expect(calendarPageSource).toContain('{#each row.week as cell (cell.dateKey)}')
    expect(calendarPageSource).toContain('month={cell.month}')
    expect(calendarPageSource).toContain('{@const cellEvents = eventsForDateKey(cell.dateKey)}')
    expect(calendarPageSource).toContain('cellEvents.slice(0, 4)')
    expect(calendarPageSource).toContain('class={monthEventRowClass()}')
    expect(calendarPageSource).toContain('class={monthEventTitleClass()}')
    expect(calendarPageSource).toContain('class={monthEventTimeClass()}')
    expect(calendarPageSource).toContain('class={monthEventMoreClass()}')
    expect(calendarPageSource).not.toContain('class={monthEventRowClass(cell.dateKey)}')
    expect(calendarPageSource).not.toContain('events: eventsForDateKey(dateKey)')
    expect(calendarPageSource).not.toContain('cell.events')
    expect(calendarPageSource).toContain('+{cellEvents.length - 4} more')
    expect(calendarPageSource).toContain('onclick={selectToday}')
    expect(calendarPageSource).toContain(
      '<Button variant="unstyled" class={`${calendarPanelActionClass} text-secondary`} onclick={selectToday}>Today</Button>'
    )
    expect(calendarPageSource).not.toContain(
      '<Button size="sm" chrome="ghost" variant="secondary" onclick={selectToday}>Today</Button>'
    )
    expect(todayHandler).toContain("if (calendarView === 'month')")
    expect(todayHandler).toContain("void scrollMonthIntoView(todayKey, 'smooth')")
    expect(todayHandler.indexOf("if (calendarView === 'month')")).toBeLessThan(
      todayHandler.indexOf('void loadCalendarViewRange({ background: true })')
    )
    expect(todayHandler).not.toContain('resetLazyMonthWindow()')
    expect(calendarPageSource).toContain('function navigateVisibleMonth')
    expect(calendarPageSource).toContain(
      '<Button variant="unstyled" class={calendarNavClass} aria-label="Previous month" onclick={() => navigateVisibleMonth(-1)}>‹</Button>'
    )
    expect(calendarPageSource).toContain(
      '<Button variant="unstyled" class={calendarNavClass} aria-label="Next month" onclick={() => navigateVisibleMonth(1)}>›</Button>'
    )
    expect(calendarPageSource).not.toContain('<button class={calendarNavClass}')
    expect(calendarPageSource).toContain('let currentMonthInViewKey = $state(viewModel.visibleAnchorKey)')
    expect(calendarPageSource).toContain('let monthScroller = $state<HTMLElement | null>(null)')
    expect(calendarPageSource).toContain('let monthScrollAnimationFrame: null | number = null')
    expect(calendarPageSource).toContain("let programmaticMonthScrollTargetKey = ''")
    expect(calendarPageSource).toContain('let programmaticMonthScrollEndTimer: null | number = null')
    expect(calendarPageSource).toContain(
      'const currentMonthInViewLabel = $derived(formatMonthHeading(currentMonthInViewKey || visibleMonth.toString()))'
    )
    expect(calendarPageSource).toContain('function handleMonthScroll()')
    expect(calendarPageSource).toContain('monthScrollFrame = window.requestAnimationFrame')
    expect(calendarPageSource).toContain('function updateHighlightedMonthFromScroll')
    expect(calendarPageSource).not.toContain("querySelectorAll<HTMLElement>('[data-calendar-week-month]')")
    expect(calendarPageSource).not.toContain("row.querySelectorAll<HTMLElement>('[data-calendar-day-month]')")
    expect(calendarPageSource).toContain('function highlightedMonthKey')
    expect(calendarPageSource).toContain('function monthGridScrollTop')
    expect(calendarPageSource).toContain('function monthWeekRowHeight')
    expect(calendarPageSource).toContain(
      'const firstVisibleIndex = clamp(Math.floor(monthGridScrollTop(scroller) / rowHeight), 0, monthVirtualGrid.weekCount - 1)'
    )
    expect(calendarPageSource).toContain('monthWeekAtIndex(monthVirtualGrid, index)')
    expect(calendarPageSource).toContain('const scores = new Map<string, VisibleMonthScore>()')
    expect(calendarPageSource).toContain('score.count += 1')
    expect(calendarPageSource).toContain('const countDelta = right[1].count - left[1].count')
    expect(calendarPageSource).toContain('data-calendar-day-month={monthStartKey(cell.dateKey)}')
    expect(calendarPageSource).toContain('data-calendar-weekday-header')
    expect(calendarPageSource).not.toContain('function highlightedMonthRow')
    expect(calendarPageSource).not.toContain('return visibleRows[1] ?? visibleRows[0]')
    expect(calendarPageSource).toContain('function scrollMonthIntoView')
    expect(calendarPageSource).toContain('function scrollMonthScroller')
    expect(calendarPageSource).toContain('const duration = Math.min(')
    expect(calendarPageSource).toContain('const eased = 1 - Math.pow(1 - progress, 3)')
    expect(calendarPageSource).toContain('monthScrollAnimationFrame = window.requestAnimationFrame(step)')
    expect(calendarPageSource).toContain('function beginProgrammaticMonthScroll')
    expect(calendarPageSource).toContain('function scheduleProgrammaticMonthScrollEnd')
    expect(calendarPageSource).toContain('if (programmaticMonthScrollTargetKey)')
    expect(calendarPageSource).toContain('currentMonthInViewKey = programmaticMonthScrollTargetKey')
    expect(calendarPageSource).toContain('function monthScrollTopForMonth')
    expect(calendarPageSource).toContain('function monthWeekIndex')
    expect(calendarPageSource).toContain('await tick()')
    expect(calendarPageSource).toContain(
      'scrollMonthScroller(scroller, monthScrollTopForMonth(targetMonthKey), targetMonthKey, behavior)'
    )
    expect(calendarPageSource).not.toContain('scroller.scrollTo({')
    expect(calendarPageSource).not.toContain('function ensureRenderedMonth')
    expect(calendarPageSource).not.toContain('await ensureRenderedMonth(targetMonthKey)')
    expect(calendarPageSource).not.toContain('const rendered = await ensureRenderedMonth(targetMonthKey)')
    expect(calendarPageSource).not.toContain('if (!rendered) return')
    expect(calendarPageSource).toContain('function maybeLoadEventsForMonth')
    expect(calendarPageSource).toContain(
      "extendEventRange('before', Math.max(eventMonthsBefore + eventLazyMonthStep, Math.abs(offset) + initialEventMonthWindow))"
    )
    expect(calendarPageSource).toContain(
      "extendEventRange('after', Math.max(eventMonthsAfter + eventLazyMonthStep, offset + initialEventMonthWindow))"
    )
    expect(calendarPageSource).toContain('function extendEventRange')
    expect(calendarPageSource).toContain(
      'void loadCalendarRange(monthRangeOptions(nextMonthsBefore, nextMonthsAfter), { background: true }).finally(() => {'
    )
    expect(calendarPageSource).not.toContain('if (!loaded) return false')
    expect(calendarPageSource).toContain('eventMonthsBefore = nextMonthsBefore')
    expect(calendarPageSource).toContain('eventMonthsAfter = nextMonthsAfter')
    expect(calendarPageSource).not.toContain('restoreMonthScrollAnchor(scroller, scrollAnchor)')
    expect(calendarPageSource).not.toContain('scroller.scrollTop += scroller.scrollHeight - previousScrollHeight')
    expect(calendarPageSource).toContain('<Loader size="md" label="Loading previous calendar events" />')
    expect(calendarPageSource).toContain('<Loader size="md" label="Loading next calendar events" />')
    expect(calendarPageSource).not.toContain('<Loader size="sm" label="Loading calendar month" />')
    expect(calendarPageSource).not.toContain('sticky top-8')
    expect(calendarPageSource).not.toContain('sticky bottom-0')
    expect(calendarPageSource).not.toContain('function resetMonthScrollerToTop()')
    expect(calendarPageSource).not.toContain('monthScroller.scrollTop = 0')
    expect(calendarPageSource).toContain('bind:this={monthScroller} onscroll={handleMonthScroll}')
    expect(calendarPageSource).toContain('data-calendar-week-month={row.monthKey}')
    expect(calendarPageSource).not.toContain('data-calendar-month={month.value.toString()}')
    expect(calendarPageSource).not.toContain(
      '<h2 class="font-hud text-base font-bold uppercase tracking-[0.12em] text-ink-bright">'
    )
    expect(calendarPageSource).toContain('{currentMonthInViewLabel}</div>')
    expect(calendarPageSource).not.toContain('{formatMonthHeading(visibleMonth.toString())}</div>')
    expect(calendarPageSource).not.toContain('<Calendar.Heading')
    expect(calendarPageSource).toContain('const eventCardClass = [')
    expect(calendarPageSource).toContain('w-full border border-line bg-surface-raised p-3 text-left transition')
    expect(calendarPageSource).not.toContain(
      'w-full rounded-panel border border-line bg-surface-raised p-3 text-left transition'
    )
    expect(calendarPageSource).toContain('hover:border-line-strong hover:bg-canvas/75')
    expect(calendarPageSource).toContain('<article class={eventCardClass}>')
    expect(calendarPageSource).toContain('grid gap-3 md:grid-cols-[minmax(0,1fr)_minmax(12rem,auto)] md:items-start')
    expect(calendarPageSource).toContain('flex flex-wrap gap-1.5 md:justify-end')
    expect(calendarPageSource).toContain(
      'mt-3 flex items-center justify-between gap-3 border-t border-line/60 pt-2 font-mono text-[0.62rem] text-ink-faint'
    )
    expect(calendarPageSource).toContain('whitespace-pre-wrap wrap-break-word')
    expect(calendarPageSource).toContain('type LinkedTextSegment')
    expect(calendarPageSource).toContain('function linkedTextSegments')
    expect(calendarPageSource).toContain('border-l border-line/70 pl-2')
    expect(calendarPageSource).toContain('{@render linkedText(event.location)}')
    expect(calendarPageSource).toContain('{@render linkedText(eventDescription(event))}')
    expect(calendarPageSource.indexOf('{@render linkedText(event.location)}')).toBeLessThan(
      calendarPageSource.indexOf('{@render linkedText(eventDescription(event))}')
    )
    expect(calendarPageSource).toContain('href={segment.href} target="_blank" rel="noreferrer"')
    expect(calendarPageSource).not.toContain('<span class="break-all"> · {event.location}</span>')
    expect(calendarPageSource).not.toContain('${eventPillClass} max-w-full truncate')
    expect(calendarPageSource).not.toContain('title={event.location}>{event.location}</span>')
    expect(calendarPageSource).not.toContain('title={event.uid}>{event.uid}</span>')
    expect(calendarPageSource).not.toContain('line-clamp-3')
    expect(calendarPageSource).not.toContain('title="DAY FEED"')
    expect(calendarPageSource).not.toContain('badge={selectedEvents.length')
    expect(calendarPageSource).not.toContain('No calendar collection configured')
    expect(calendarPageSource).not.toContain('viewModel.configStatus?.calendarUrl')
    expect(calendarPageSource).not.toContain('viewModel.configStatus?.username')
    expect(visibleMonthHandler).toContain('visibleMonth = value')
    expect(visibleMonthHandler).toContain('currentMonthInViewKey = monthStartKey(value.toString())')
    expect(visibleMonthHandler).toContain('viewModel.setVisibleAnchor(value.toString())')
    expect(visibleMonthHandler).toContain("void scrollMonthIntoView(value.toString(), 'auto')")
    expect(visibleMonthHandler).not.toContain('loadCalendarViewRange')
    expect(visibleMonthHandler).not.toContain('viewModel.loadVisibleRange')
    expect(visibleMonthHandler).not.toContain('viewModel.refresh')
    expect(visibleMonthHandler).not.toContain('viewModel.syncNow')
  })
})
