import { describe, expect, it } from 'vitest'

import composerSource from '../components/composer/Composer.svelte?raw'
import dashboardSource from './dashboard.ts?raw'
import mainAgentPanelSource from './MainAgentPanel.svelte?raw'
import mainContainersPanelSource from './MainContainersPanel.svelte?raw'
import mainPageSource from './MainPage.svelte?raw'
import mainRenderPanelSource from './MainRenderPanel.svelte?raw'
import mainRenderSceneSource from './MainRenderScene.svelte?raw'
import monitoringAdapterSource from '$lib/monitoring/adapters/beszel-monitoring-adapter.ts?raw'
import monitoringMetricsApplicationSource from '$lib/monitoring/application/get-monitoring-metrics.ts?raw'

describe('Main dashboard source contract', () => {
  it('renders monitoring, containers, desktop AGENT panel, and mobile AGENT link without dashboard header/footer chrome', () => {
    expect(mainPageSource).toContain('recentDashboardSessions')
    expect(mainPageSource).toContain('fetchMonitoringMetrics')
    expect(mainPageSource).toContain('monitoringConfig')
    expect(mainPageSource).toContain('sessionState.sessions')
    expect(mainPageSource).toContain('MONITORING')
    expect(mainPageSource).toContain('Disk Usage')
    expect(mainPageSource).toContain('CPU NAME')
    expect(mainPageSource).toContain('TOTAL RAM')
    expect(mainPageSource).toContain('formatPercent(monitoringMetrics.disk.usedPercent)')
    expect(mainPageSource).toContain('formatBytes(monitoringMetrics.disk.usedBytes)')
    expect(mainPageSource).toContain('formatBytes(monitoringMetrics.disk.totalBytes)')
    expect(mainPageSource).toContain('MainContainersPanel')
    expect(mainContainersPanelSource).toContain('title="CONTAINERS"')
    expect(mainContainersPanelSource).toContain('{containerCount} containers')
    expect(mainContainersPanelSource).toContain('Container')
    expect(mainPageSource).toContain('dashboardPanelClass')
    expect(mainPageSource).toContain('raisedPanelClass')
    expect(mainPageSource).toContain('{#each monitoringSystemStats as stat')
    expect(mainPageSource).toContain('{#each monitoringUsageRows as row')
    expect(mainPageSource).not.toContain('remoteTemperatureRows')
    expect(mainPageSource).not.toContain('REMOTE TEMP')
    expect(mainPageSource).not.toContain('No remote thermal sensors reported.')
    expect(mainPageSource).toContain('{#each placeholderPanels as placeholder')
    expect(mainPageSource).toContain('{#each kanbanStats as stat')
    expect(mainPageSource).toContain('<Panel flat fullHeight={false} padded={false} class={raisedPanelClass}')
    expect(mainPageSource).not.toContain('border border-line bg-surface-raised p-2')
    expect(mainContainersPanelSource).toContain(
      "let containerSortDirection = $state<MonitoringContainerSortDirection>('desc')"
    )
    expect(mainContainersPanelSource).toContain('toggleContainerSort')
    expect(mainContainersPanelSource).toContain(
      'sortMonitoringContainers(metrics.containers, containerSortKey, containerSortDirection)'
    )
    expect(mainContainersPanelSource).toContain("onclick={() => toggleContainerSort('cpu')}")
    expect(mainContainersPanelSource).toContain("onclick={() => toggleContainerSort('memory')}")
    expect(mainContainersPanelSource).toContain('MEM{containerSortLabel')
    expect(mainContainersPanelSource).toContain('return formatBytes(container.memoryBytes)')
    expect(mainContainersPanelSource).not.toContain('formatPercent(container.memoryPercent)')
    expect(mainContainersPanelSource).not.toContain('containerSortVariant')
    expect(mainContainersPanelSource).not.toContain("onclick={() => (containerSortKey = 'cpu')}")
    expect(mainContainersPanelSource).not.toContain("onclick={() => (containerSortKey = 'memory')}")
    expect(mainPageSource).toContain('grid-cols-1')
    expect(mainPageSource).toContain('md:grid-cols-[minmax(0,0.9fr)_minmax(0,1.12fr)_minmax(0,0.86fr)]')
    expect(mainPageSource).toContain('md:grid-rows-[minmax(0,1.45fr)_minmax(0,0.55fr)]')
    expect(mainPageSource).toContain('min-h-56 flex-1')
    expect(mainPageSource).not.toContain('badge={monitorStatus}')
    expect(mainPageSource).not.toContain('monitorStatus')
    expect(mainPageSource).toMatch(/title="MONITORING"[\s\S]*MainContainersPanel[\s\S]*MainAgentPanel/)
    expect(mainAgentPanelSource).toContain('title="AGENT"')
    expect(mainPageSource).toContain('class="hidden h-full min-h-0 md:block"')
    expect(mainPageSource).toContain('class={`${dashboardPanelClass} md:hidden`}')
    expect(mainPageSource).toContain('badge="link"')
    expect(mainContainersPanelSource).toContain('aria-label="Containers"')
    expect(mainPageSource).not.toContain('grid-rows-[minmax(0,0.72fr)_minmax(0,1.28fr)]')
    expect(mainPageSource).not.toContain('PROCESS_LIST')
    expect(mainPageSource).not.toContain('aria-label="Process list"')
    expect(mainPageSource).not.toContain('SESSIONS')
    expect(mainPageSource).not.toContain('THREADS')
    expect(mainPageSource).not.toContain('readonly')
    expect(mainContainersPanelSource).toContain('containerEmptyLabel')
    expect(mainContainersPanelSource).toContain('No Beszel containers reported for this system.')
    expect(mainPageSource).toContain('CPU Usage')
    expect(mainPageSource).toContain('Mem Usage')
    expect(mainPageSource).toContain('Disk Usage')
    expect(mainPageSource).not.toContain('barClass')
    expect(mainPageSource).not.toContain('valueClass')
    expect(mainPageSource).not.toContain("monitoringMetrics.version.startsWith('beszel')")
    expect(`${mainPageSource}\n${mainContainersPanelSource}`).not.toContain('Read-only process list')
    expect(mainPageSource).not.toContain('HOST_LINK')
    expect(mainPageSource).not.toContain('CPU_STATS')
    expect(mainPageSource).not.toContain('MEMORY_STATS')
    expect(mainPageSource).not.toContain('CPU_LOAD')
    expect(mainPageSource).not.toContain('RAM_USED')
    expect(mainPageSource).not.toContain('<header')
    expect(mainPageSource).not.toContain('<footer')
    expect(mainPageSource).not.toContain('Dashboard page placeholder')
  })

  it('uses Threlte for the render panel and reflects CPU/RAM load in shape scale', () => {
    expect(mainPageSource).toContain('MainRenderPanel')
    expect(mainRenderPanelSource).toContain("import { Canvas } from '@threlte/core'")
    expect(mainRenderPanelSource).toContain("import Panel from '@/app/components/ui/Panel.svelte'")
    expect(mainRenderPanelSource).toContain('// RENDER')
    expect(mainRenderPanelSource).not.toContain('// RENDER_')
    expect(mainRenderSceneSource).toContain("import { T, useTask } from '@threlte/core'")
    expect(mainRenderSceneSource).toContain('cpuUsagePercent')
    expect(mainRenderSceneSource).toContain('memoryUsagePercent')
    expect(mainRenderSceneSource).toContain('cpuShape')
    expect(mainRenderSceneSource).toContain('LineSegments')
    expect(mainRenderPanelSource).toContain('--color-ink-bright')
    expect(mainRenderPanelSource).toContain('--color-ink-muted')
    expect(mainRenderPanelSource).toContain('--color-line-strong')
    expect(mainRenderSceneSource).toContain('foregroundColor')
    expect(mainRenderSceneSource).toContain('mutedColor')
    expect(`${mainRenderPanelSource}\n${mainRenderSceneSource}`).not.toMatch(/#8be9fd|#bd93f9|#ff79c6/)
    expect(mainPageSource).not.toContain('Glyph')
  })

  it('loads Beszel monitoring endpoint config from MONITORING_URL', () => {
    const monitoringSource = `${monitoringAdapterSource}\n${monitoringMetricsApplicationSource}`

    expect(monitoringAdapterSource).toContain('__MONITORING_SYSTEM_ID__')
    expect(monitoringAdapterSource).toContain('__MONITORING_URL__')
    expect(monitoringAdapterSource).toContain('monitoring_request')
    expect(monitoringAdapterSource).toContain('http://homestation:8090')
    expect(monitoringSource).toContain('/api/collections')
    expect(monitoringSource).toContain('BESZEL_COLLECTIONS')
    expect(monitoringSource).toContain("containers: 'containers'")
    expect(monitoringSource).toContain('BESZEL_CONTAINER_FIELDS')
    expect(monitoringSource).toContain("systemStats: 'system_stats'")
    expect(monitoringSource).not.toContain('GLANCES_ENDPOINTS')
    expect(monitoringSource).not.toContain('normalizeLegacyMonitoringMetrics')
    expect(monitoringSource).not.toContain('quicklook')
    expect(monitoringSource).not.toContain('/api/4')
    expect(monitoringSource).not.toContain('processlist')
  })

  it('loads remote dashboard state instead of offering local Hermes bootstrap controls', () => {
    expect(mainPageSource).toContain('refreshActiveProfile')
    expect(mainPageSource).toContain('initializeSessions')
    expect(mainPageSource).toContain("connectionState !== 'open'")
    expect(`${mainPageSource}\n${dashboardSource}`).not.toMatch(
      /local Hermes bootstrap|BITCH_GATEWAY_URL|VITE_BOX_BASE_URL|Dufs|bitch\.plugin/i
    )
  })

  it('keeps the embedded AGENT conversation/composer on desktop while mobile uses an AGENT link', () => {
    expect(mainPageSource).toContain("import { agentRoute, cronRoute, kanbanRoute } from '../router.svelte'")
    expect(mainPageSource).toContain("import MainAgentPanel from './MainAgentPanel.svelte'")
    expect(mainPageSource).toContain('const agentHref')
    expect(mainPageSource).toContain('<MainAgentPanel fallbackSessionId={miniSessionFallbackId} />')
    expect(mainPageSource).toContain('class="hidden h-full min-h-0 md:block"')
    expect(mainPageSource).toContain('class={`${dashboardPanelClass} md:hidden`}')
    expect(mainPageSource).toContain('href={agentHref}')
    expect(mainPageSource).toContain('aria-label="Open AGENT tab"')
    expect(mainPageSource).toContain('Open AGENT')
    expect(mainPageSource).toContain('Main stays telemetry-first on mobile')
    expect(mainAgentPanelSource).toContain("import Composer from '../components/composer/Composer.svelte'")
    expect(mainAgentPanelSource).toContain("import Conversation from '../components/conversation/Conversation.svelte'")
    expect(mainAgentPanelSource).toContain("import Button from '@/app/components/ui/Button.svelte'")
    expect(mainAgentPanelSource).toContain("import Dialog from '@/app/components/ui/Dialog.svelte'")
    expect(mainAgentPanelSource).toContain("import { agentRoute } from '../router.svelte'")
    expect(mainAgentPanelSource).toContain('resumeAndHydrateStoredSession')
    expect(mainAgentPanelSource).toContain("type MiniSessionMode = 'active' | 'new'")
    expect(mainAgentPanelSource).toContain('title="AGENT"')
    expect(mainAgentPanelSource).toContain('href={agentHref}')
    expect(mainAgentPanelSource).toContain('aria-label="Open current chat in AGENT"')
    expect(mainAgentPanelSource).toContain('aria-haspopup="dialog"')
    expect(mainAgentPanelSource).toContain('SESSION')
    expect(mainAgentPanelSource).toContain('title="Select AGENT Session"')
    expect(mainAgentPanelSource).toContain('New session')
    expect(mainAgentPanelSource).toContain('startNewSession({ commitRoute: false })')
    expect(mainAgentPanelSource).toContain('compact')
    expect(mainAgentPanelSource).toContain('commitRoute={false}')
    expect(composerSource).toContain("? 'shrink-0 bg-surface-raised/35 p-2'")
  })

  it('renders Calendar placeholder plus wired Cron and Kanban dashboard panels', () => {
    expect(mainPageSource).toContain('CALENDAR')
    expect(mainPageSource).toContain('CRON')
    expect(mainPageSource).toContain('KANBAN')
    expect(mainPageSource).not.toContain('KANBAN_SUMMARY')
    expect(mainPageSource).toContain('placeholder')
    expect(mainPageSource).toContain('const cronHref')
    expect(mainPageSource).toContain('href={cronHref}')
    expect(mainPageSource).toContain('Open Cron')
    expect(mainPageSource).toContain('badge="ready"')
    expect(mainPageSource).toContain('href={kanbanHref}')
    expect(mainPageSource).toContain('Open Kanban')
    expect(dashboardSource).toContain("id: 'calendar'")
    expect(dashboardSource).toContain('href: `#${calendarRoute()}`')
    expect(dashboardSource).toContain("id: 'cron'")
    expect(dashboardSource).toContain('href: `#${cronRoute()}`')
    expect(dashboardSource).toContain("id: 'kanban'")
    expect(dashboardSource).toContain('href: `#${kanbanRoute()}`')
    expect(dashboardSource).not.toContain("state: 'planned'")
  })
})
