import { describe, expect, it } from 'vitest'

import dashboardSource from './dashboard.ts?raw'
import mainPageSource from './MainPage.svelte?raw'
import mainRenderPanelSource from './MainRenderPanel.svelte?raw'
import mainRenderSceneSource from './MainRenderScene.svelte?raw'
import hostMonitorSource from '$lib/host-monitor.ts?raw'

describe('Main dashboard source contract', () => {
  it('renders hardware, process, and AGENT-link sections without dashboard header/footer chrome', () => {
    expect(mainPageSource).toContain('recentDashboardSessions')
    expect(mainPageSource).toContain('fetchHostMetrics')
    expect(mainPageSource).toContain('hostMonitorConfig')
    expect(mainPageSource).toContain('sessionState.sessions')
    expect(mainPageSource).toContain('HARDWARE')
    expect(mainPageSource).toContain('DISK')
    expect(mainPageSource).toContain('formatPercent(hostMetrics.disk.usedPercent)')
    expect(mainPageSource).not.toContain('formatBytes(hostMetrics.disk')
    expect(mainPageSource).toContain('title="PROCESS"')
    expect(mainPageSource).toContain('dashboardPanelClass')
    expect(mainPageSource).toContain('raisedPanelClass')
    expect(mainPageSource).toContain('{#each hardwareStats as stat')
    expect(mainPageSource).toContain('{#each hardwareUsageRows as row')
    expect(mainPageSource).not.toContain('remoteTemperatureRows')
    expect(mainPageSource).not.toContain('REMOTE TEMP')
    expect(mainPageSource).not.toContain('No remote thermal sensors reported.')
    expect(mainPageSource).toContain('{#each placeholderPanels as placeholder')
    expect(mainPageSource).toContain('{#each kanbanStats as stat')
    expect(mainPageSource).toContain('<Panel flat fullHeight={false} padded={false} class={raisedPanelClass}')
    expect(mainPageSource).not.toContain('border border-line bg-surface-raised p-2')
    expect(mainPageSource).toContain("let processSortDirection = $state<HostProcessSortDirection>('desc')")
    expect(mainPageSource).toContain('toggleProcessSort')
    expect(mainPageSource).toContain('sortHostProcesses(hostMetrics.processes, processSortKey, processSortDirection)')
    expect(mainPageSource).toContain("onclick={() => toggleProcessSort('cpu')}")
    expect(mainPageSource).toContain("onclick={() => toggleProcessSort('memory')}")
    expect(mainPageSource).toContain('MEM{processSortLabel')
    expect(mainPageSource).toContain('return formatBytes(process.memoryBytes)')
    expect(mainPageSource).not.toContain('formatPercent(process.memoryPercent)')
    expect(mainPageSource).not.toContain('processSortVariant')
    expect(mainPageSource).not.toContain("onclick={() => (processSortKey = 'cpu')}")
    expect(mainPageSource).not.toContain("onclick={() => (processSortKey = 'memory')}")
    expect(mainPageSource).toContain('grid-cols-1')
    expect(mainPageSource).toContain('md:grid-cols-[minmax(0,1.25fr)_minmax(18rem,0.75fr)]')
    expect(mainPageSource).toContain('md:grid-rows-[minmax(0,1.45fr)_minmax(0,0.55fr)]')
    expect(mainPageSource).toContain('min-h-56 flex-1')
    expect(mainPageSource).not.toContain('badge={monitorStatus}')
    expect(mainPageSource).not.toContain('monitorStatus')
    expect(mainPageSource).toMatch(/title="HARDWARE"[\s\S]*title="PROCESS"[\s\S]*title="AGENT"/)
    expect(mainPageSource).toContain('badge="link"')
    expect(mainPageSource).not.toContain('MainAgentPanel')
    expect(mainPageSource).toContain('aria-label="Process"')
    expect(mainPageSource).not.toContain('grid-rows-[minmax(0,0.72fr)_minmax(0,1.28fr)]')
    expect(mainPageSource).not.toContain('PROCESS_LIST')
    expect(mainPageSource).not.toContain('aria-label="Process list"')
    expect(mainPageSource).not.toContain('SESSIONS')
    expect(mainPageSource).not.toContain('THREADS')
    expect(mainPageSource).not.toContain('readonly')
    expect(mainPageSource).not.toContain('Read-only process list')
    expect(mainPageSource).not.toContain('HOST_LINK')
    expect(mainPageSource).not.toContain('CPU_STATS')
    expect(mainPageSource).not.toContain('MEMORY_STATS')
    expect(mainPageSource).not.toContain('CPU_LOAD')
    expect(mainPageSource).not.toContain('RAM_USED')
    expect(mainPageSource).not.toContain('<header')
    expect(mainPageSource).not.toContain('<footer')
    expect(mainPageSource).not.toContain('Dashboard page placeholder')
  })

  it('uses Threlte for the render panel and reflects CPU/RAM load in shape scale', () => {
    expect(mainPageSource).toContain('MainRenderPanel')
    expect(mainRenderPanelSource).toContain("import { Canvas } from '@threlte/core'")
    expect(mainRenderPanelSource).toContain("import Panel from '@/app/components/ui/Panel.svelte'")
    expect(mainRenderPanelSource).toContain('// RENDER')
    expect(mainRenderPanelSource).not.toContain('// RENDER_')
    expect(mainRenderSceneSource).toContain("import { T, useTask } from '@threlte/core'")
    expect(mainRenderSceneSource).toContain('cpuUsagePercent')
    expect(mainRenderSceneSource).toContain('memoryUsagePercent')
    expect(mainRenderSceneSource).toContain('cpuShape')
    expect(mainRenderSceneSource).toContain('LineSegments')
    expect(mainPageSource).not.toContain('Glyph')
  })

  it('loads host monitor endpoint config from HOST_MONITOR_URL', () => {
    expect(hostMonitorSource).toContain('__HOST_MONITOR_URL__')
    expect(hostMonitorSource).toContain('http://homestation:61208')
    expect(hostMonitorSource).toContain('/api/4')
    expect(hostMonitorSource).toContain('GLANCES_ENDPOINTS')
    expect(hostMonitorSource).toContain("fs: '/fs'")
    expect(hostMonitorSource).toContain('processlist')
  })

  it('loads remote dashboard state instead of offering local Hermes bootstrap controls', () => {
    expect(mainPageSource).toContain('refreshActiveProfile')
    expect(mainPageSource).toContain('initializeSessions')
    expect(mainPageSource).toContain("connectionState !== 'open'")
    expect(`${mainPageSource}\n${dashboardSource}`).not.toMatch(
      /local Hermes bootstrap|BITCH_GATEWAY_URL|VITE_BOX_BASE_URL|Dufs|bitch\.plugin/i
    )
  })

  it('links to the full AGENT tab instead of embedding a dashboard agent panel', () => {
    expect(mainPageSource).toContain("import { agentRoute } from '../router.svelte'")
    expect(mainPageSource).toContain('const agentHref')
    expect(mainPageSource).toContain('href={agentHref}')
    expect(mainPageSource).toContain('aria-label="Open AGENT tab"')
    expect(mainPageSource).toContain('Open AGENT')
    expect(mainPageSource).toContain('Main stays telemetry-first on mobile')
    expect(mainPageSource).not.toContain('Thread compact')
    expect(mainPageSource).not.toContain('<Composer')
    expect(mainPageSource).not.toContain('resumeAndHydrateStoredSession')
  })

  it('renders Calendar, Cron, and Kanban dashboard panels while only Cron/Kanban remain planned', () => {
    expect(mainPageSource).toContain('CALENDAR')
    expect(mainPageSource).toContain('CRON')
    expect(mainPageSource).toContain('KANBAN')
    expect(mainPageSource).not.toContain('KANBAN_SUMMARY')
    expect(mainPageSource).toContain('placeholder')
    expect(dashboardSource).toContain("id: 'calendar'")
    expect(dashboardSource).toContain('href: `#${calendarRoute()}`')
    expect(dashboardSource).toContain("id: 'cron'")
    expect(dashboardSource).toContain("id: 'kanban'")
    expect(dashboardSource).toContain("state: 'planned'")
  })
})
