import { describe, expect, it } from 'vitest'

import composerSource from '../../components/composer/Composer.svelte?raw'
import dashboardSource from '../../main/dashboard.ts?raw'
import mainPageSource from '../../main/MainPage.svelte?raw'
import mainAgentPanelSource from '../../main/panels/MainAgentPanel.svelte?raw'
import mainContainersPanelSource from '../../main/panels/MainContainersPanel.svelte?raw'
import mainCronPanelSource from '../../main/panels/MainCronPanel.svelte?raw'
import mainKanbanPanelSource from '../../main/panels/MainKanbanPanel.svelte?raw'
import buttonSource from '../../components/ui/Button.svelte?raw'
import glyphSource from '../../components/Glyph.svelte?raw'
import mainGlyphPanelSource from '../../main/panels/MainGlyphPanel.svelte?raw'
import monitoringAdapterSource from '$lib/monitoring/adapters/beszel-monitoring-adapter.ts?raw'
import monitoringMetricsApplicationSource from '$lib/monitoring/application/get-monitoring-metrics.ts?raw'

describe('Main dashboard source contract', () => {
  it('renders monitoring, containers, desktop AGENT panel, and compact mobile AGENT cards without dashboard header/footer chrome', () => {
    expect(mainPageSource).toContain('recentDashboardSessions')
    expect(mainPageSource).toContain('fetchMonitoringMetrics')
    expect(mainPageSource).toContain('monitoringConfig')
    expect(mainPageSource).toContain('sessionState.sessions')
    expect(mainPageSource).toContain('MONITORING')
    expect(mainPageSource).toContain('Disk Usage')
    expect(mainPageSource).toContain('CPU NAME')
    expect(mainPageSource).toContain('TOTAL RAM')
    expect(mainPageSource).toContain('formatPercent(monitoringMetrics.disk.usedPercent)')
    expect(mainPageSource).toContain('formatBytes(monitoringMetrics.disk.usedBytes)')
    expect(mainPageSource).toContain('formatBytes(monitoringMetrics.disk.totalBytes)')
    expect(mainPageSource).toContain('MainContainersPanel')
    expect(mainContainersPanelSource).toContain('title="CONTAINERS"')
    expect(mainContainersPanelSource).toContain('{containerCount} containers')
    expect(mainContainersPanelSource).toContain('Container')
    expect(mainPageSource).toContain('dashboardPanelClass')
    expect(`${mainCronPanelSource}\n${mainKanbanPanelSource}`).toContain('raisedPanelClass')
    expect(mainPageSource).toContain('{#each monitoringSystemStats as stat')
    expect(mainPageSource).toContain('{#each monitoringUsageRows as row')
    expect(mainPageSource).not.toContain('remoteTemperatureRows')
    expect(mainPageSource).not.toContain('REMOTE TEMP')
    expect(mainPageSource).not.toContain('No remote thermal sensors reported.')
    expect(mainPageSource).toContain('{#each placeholderPanels as placeholder')
    expect(mainKanbanPanelSource).toContain('{#each kanbanStats as stat')
    expect(`${mainCronPanelSource}\n${mainKanbanPanelSource}`).toContain(
      '<Panel flat fullHeight={false} padded={false} class={raisedPanelClass}'
    )
    expect(mainPageSource).not.toContain('border border-line bg-surface-raised p-2')
    expect(mainContainersPanelSource).toContain(
      "let containerSortDirection = $state<MonitoringContainerSortDirection>('desc')"
    )
    expect(mainContainersPanelSource).toContain('toggleContainerSort')
    expect(mainContainersPanelSource).toContain(
      'sortMonitoringContainers(metrics.containers, containerSortKey, containerSortDirection)'
    )
    expect(mainContainersPanelSource).toContain("onclick={() => toggleContainerSort('cpu')}")
    expect(mainContainersPanelSource).toContain("onclick={() => toggleContainerSort('memory')}")
    expect(mainContainersPanelSource).toContain('MEM{containerSortLabel')
    expect(mainContainersPanelSource).toContain('return formatBytes(container.memoryBytes)')
    expect(mainContainersPanelSource).not.toContain('formatPercent(container.memoryPercent)')
    expect(mainContainersPanelSource).not.toContain('containerSortVariant')
    expect(mainContainersPanelSource).not.toContain("onclick={() => (containerSortKey = 'cpu')}")
    expect(mainContainersPanelSource).not.toContain("onclick={() => (containerSortKey = 'memory')}")
    expect(mainPageSource).toContain('grid-cols-1')
    expect(mainPageSource).toContain('md:grid-cols-[minmax(0,0.9fr)_minmax(0,1.12fr)_minmax(0,0.86fr)]')
    expect(mainPageSource).toContain('md:grid-rows-[minmax(0,0.85fr)_auto_minmax(0,1fr)]')
    expect(mainPageSource).toContain('MainGlyphPanel')
    expect(mainPageSource).toContain('min-h-56 md:min-h-0')
    expect(mainGlyphPanelSource).toContain('title="GLYPH"')
    expect(mainPageSource).not.toContain('min-h-56 flex-1')
    expect(mainPageSource).not.toContain('badge={monitorStatus}')
    expect(mainPageSource).not.toContain('monitorStatus')
    expect(mainPageSource).toMatch(
      /MainGlyphPanel[\s\S]*title="MONITORING"[\s\S]*MainContainersPanel[\s\S]*MainAgentPanel/
    )
    expect(mainAgentPanelSource).toContain('title="AGENT"')
    expect(mainPageSource).toContain('class="hidden h-full min-h-0 min-w-0 md:block"')
    expect(mainPageSource).toContain('class={`${dashboardPanelClass} order-2 md:hidden md:order-0`}')
    expect(mainPageSource).not.toContain('badge="link"')
    expect(mainContainersPanelSource).toContain('aria-label="Containers"')
    expect(mainPageSource).not.toContain('grid-rows-[minmax(0,0.72fr)_minmax(0,1.28fr)]')
    expect(mainPageSource).not.toContain('PROCESS_LIST')
    expect(mainPageSource).not.toContain('aria-label="Process list"')
    expect(mainPageSource).not.toContain('SESSIONS')
    expect(mainPageSource).not.toContain('THREADS')
    expect(mainPageSource).not.toContain('readonly')
    expect(mainContainersPanelSource).toContain('containerEmptyLabel')
    expect(mainContainersPanelSource).toContain('No Beszel containers reported for this system.')
    expect(mainPageSource).toContain('CPU Usage')
    expect(mainPageSource).toContain('Mem Usage')
    expect(mainPageSource).toContain('Disk Usage')
    expect(mainPageSource).not.toContain('barClass')
    expect(mainPageSource).not.toContain('valueClass')
    expect(mainPageSource).not.toContain("monitoringMetrics.version.startsWith('beszel')")
    expect(`${mainPageSource}\n${mainContainersPanelSource}`).not.toContain('Read-only process list')
    expect(mainPageSource).not.toContain('HOST_LINK')
    expect(mainPageSource).not.toContain('CPU_STATS')
    expect(mainPageSource).not.toContain('MEMORY_STATS')
    expect(mainPageSource).not.toContain('CPU_LOAD')
    expect(mainPageSource).not.toContain('RAM_USED')
    expect(mainPageSource).not.toContain('<header')
    expect(mainPageSource).not.toContain('<footer')
    expect(mainPageSource).not.toContain('Dashboard page placeholder')
  })

  it('uses the shared Threlte glyph for the GLYPH panel and reflects CPU/RAM load in shape scale', () => {
    expect(mainPageSource).toContain('MainGlyphPanel')
    expect(mainGlyphPanelSource).toContain("import { Canvas } from '@threlte/core'")
    expect(mainGlyphPanelSource).toContain("import Glyph from '@/app/components/Glyph.svelte'")
    expect(mainGlyphPanelSource).toContain("import Panel from '@/app/components/ui/Panel.svelte'")
    expect(mainGlyphPanelSource).toContain('title="GLYPH"')
    expect(mainPageSource).toContain('hostname={monitoringMetrics.systemName}')
    expect(mainGlyphPanelSource).toContain('hostname: string')
    expect(mainGlyphPanelSource).toContain("// {hostname || 'UNKNOWN'}")
    expect(mainGlyphPanelSource).not.toContain('// RENDER')
    expect(glyphSource).toContain("import { T, useTask } from '@threlte/core'")
    expect(glyphSource).toContain('animated?: boolean')
    expect(glyphSource).toContain('cpuUsagePercent')
    expect(glyphSource).toContain('memoryUsagePercent')
    expect(glyphSource).toContain('cpuShape')
    expect(glyphSource).toContain('LineSegments')
    expect(mainGlyphPanelSource).toContain('--color-ink-bright')
    expect(mainGlyphPanelSource).toContain('--color-ink-muted')
    expect(mainGlyphPanelSource).toContain('--color-line-strong')
    expect(glyphSource).toContain('foregroundColor')
    expect(glyphSource).toContain('mutedColor')
    expect(`${mainGlyphPanelSource}\n${glyphSource}`).not.toMatch(/#8be9fd|#bd93f9|#ff79c6/)
  })

  it('loads Beszel monitoring endpoint config from MONITORING_URL', () => {
    const monitoringSource = `${monitoringAdapterSource}\n${monitoringMetricsApplicationSource}`

    expect(monitoringAdapterSource).toContain('__MONITORING_SYSTEM_ID__')
    expect(monitoringAdapterSource).toContain('__MONITORING_URL__')
    expect(monitoringAdapterSource).toContain('monitoring_request')
    expect(monitoringAdapterSource).toContain('http://homestation:8090')
    expect(monitoringSource).toContain('/api/collections')
    expect(monitoringSource).toContain('BESZEL_COLLECTIONS')
    expect(monitoringSource).toContain("containers: 'containers'")
    expect(monitoringSource).toContain('BESZEL_CONTAINER_FIELDS')
    expect(monitoringSource).toContain("systemStats: 'system_stats'")
    expect(monitoringSource).not.toContain('GLANCES_ENDPOINTS')
    expect(monitoringSource).not.toContain('normalizeLegacyMonitoringMetrics')
    expect(monitoringSource).not.toContain('quicklook')
    expect(monitoringSource).not.toContain('/api/4')
    expect(monitoringSource).not.toContain('processlist')
  })

  it('loads remote dashboard state instead of offering local Hermes bootstrap controls', () => {
    expect(mainPageSource).toContain('refreshActiveProfile')
    expect(mainPageSource).toContain('initializeSessions')
    expect(mainPageSource).toContain("connectionState !== 'open'")
    expect(`${mainPageSource}\n${dashboardSource}`).not.toMatch(
      /local Hermes bootstrap|BITCH_GATEWAY_URL|VITE_BOX_BASE_URL|Dufs|bitch\.plugin/i
    )
  })

  it('keeps the embedded AGENT conversation/composer on desktop while mobile uses compact AGENT cards', () => {
    expect(mainPageSource).toContain("import { agentRoute } from '../router.svelte'")
    expect(mainPageSource).toContain("import MainAgentPanel from './panels/MainAgentPanel.svelte'")
    expect(mainPageSource).toContain('const newAgentHref')
    expect(mainPageSource).toContain('mobileAgentSession')
    expect(mainPageSource).toContain('<MainAgentPanel fallbackSessionId={miniSessionFallbackId} />')
    expect(mainPageSource).toContain('class="hidden h-full min-h-0 min-w-0 md:block"')
    expect(mainPageSource).toContain('class={`${dashboardPanelClass} order-2 md:hidden md:order-0`}')
    expect(mainPageSource).toContain('href={mobileAgentSession.href}')
    expect(mainPageSource).toContain('href={newAgentHref}')
    expect(mainPageSource).toContain('aria-label="Start a new AGENT session"')
    expect(mainPageSource).toContain('New session')
    expect(mainPageSource).toContain('Last session')
    expect(mainAgentPanelSource).toContain("import Composer from '../../components/composer/Composer.svelte'")
    expect(mainAgentPanelSource).toContain(
      "import Conversation from '../../components/conversation/Conversation.svelte'"
    )
    expect(mainAgentPanelSource).toContain("import Button from '@/app/components/ui/Button.svelte'")
    expect(mainAgentPanelSource).toContain("import Dialog from '@/app/components/ui/Dialog.svelte'")
    expect(mainAgentPanelSource).toContain("import { agentRoute } from '../../router.svelte'")
    expect(mainAgentPanelSource).toContain('resumeAndHydrateStoredSession')
    expect(mainAgentPanelSource).toContain("type MiniSessionMode = 'active' | 'new'")
    expect(mainAgentPanelSource).toContain('title="AGENT"')
    expect(mainAgentPanelSource).toContain('href={agentHref}')
    expect(mainAgentPanelSource).toContain('aria-label="Open current chat in AGENT"')
    expect(mainAgentPanelSource).toContain('aria-haspopup="dialog"')
    expect(mainAgentPanelSource).toContain('SESSION')
    expect(mainAgentPanelSource).toContain('title="Select AGENT Session"')
    expect(mainAgentPanelSource).toContain('New session')
    expect(mainAgentPanelSource).toContain('startNewSession({ commitRoute: false })')
    expect(mainAgentPanelSource).toContain('compact')
    expect(mainAgentPanelSource).toContain('commitRoute={false}')
    expect(composerSource).toContain("? 'shrink-0 bg-surface-raised/35 p-2'")
  })

  it('renders Calendar placeholder plus wired Cron and Kanban dashboard panels', () => {
    expect(mainPageSource).toContain('CALENDAR')
    expect(mainCronPanelSource).toContain('title="CRON"')
    expect(mainKanbanPanelSource).toContain('title="KANBAN"')
    expect(mainPageSource).not.toContain('KANBAN_SUMMARY')
    expect(mainPageSource).toContain('placeholder')
    expect(mainPageSource).toContain("import MainAgentPanel from './panels/MainAgentPanel.svelte'")
    expect(mainPageSource).toContain("import MainContainersPanel from './panels/MainContainersPanel.svelte'")
    expect(mainPageSource).toContain("import MainCronPanel from './panels/MainCronPanel.svelte'")
    expect(mainPageSource).toContain("import MainGlyphPanel from './panels/MainGlyphPanel.svelte'")
    expect(mainPageSource).toContain("import MainKanbanPanel from './panels/MainKanbanPanel.svelte'")
    expect(mainPageSource).toContain(
      '<MainCronPanel class={`${dashboardPanelClass} order-4 md:order-0`} titleClass={dashboardPanelTitleClass} />'
    )
    expect(mainPageSource).toContain(
      '<MainKanbanPanel class={`${dashboardPanelClass} order-3 md:order-0`} titleClass={dashboardPanelTitleClass} />'
    )
    expect(mainCronPanelSource).toContain("import { cronRoute } from '../../router.svelte'")
    expect(mainKanbanPanelSource).toContain("import { kanbanRoute } from '../../router.svelte'")
    expect(mainCronPanelSource).toContain('const cronHref')
    expect(mainCronPanelSource).toContain("import Button from '@/app/components/ui/Button.svelte'")
    expect(mainKanbanPanelSource).toContain("import Button from '@/app/components/ui/Button.svelte'")
    expect(buttonSource).toContain('{#if href}')
    expect(buttonSource).toContain('<a {href} class={classes} {...anchorRest}>')
    expect(mainCronPanelSource).toContain('getCronJobs')
    expect(mainCronPanelSource).toContain('refreshCronJobs')
    expect(mainCronPanelSource).toContain('cronFocusJobs')
    expect(mainCronPanelSource).toContain('Run queue')
    expect(mainCronPanelSource).toContain("{ label: 'Jobs'")
    expect(mainCronPanelSource).toContain("{ label: 'Paused'")
    expect(mainCronPanelSource).toContain("{ label: 'Alerts'")
    expect(mainCronPanelSource).toContain('href={cronHref}')
    expect(mainCronPanelSource).toContain('<Button size="sm" chrome="ghost" variant="secondary" href={cronHref}')
    expect(mainCronPanelSource).toContain('Open Cron')
    expect(mainCronPanelSource).not.toContain('Scheduler surface online')
    expect(mainCronPanelSource).not.toContain(
      'Cron route manages Hermes jobs through the authenticated dashboard cron API'
    )
    expect(mainCronPanelSource).not.toMatch(/title="CRON"[\s\S]{0,120}badge="ready"/)
    expect(mainKanbanPanelSource).not.toMatch(/title="KANBAN"[\s\S]{0,120}badge="ready"/)
    expect(mainKanbanPanelSource).toContain('href={kanbanHref}')
    expect(mainKanbanPanelSource).toContain('<Button size="sm" chrome="ghost" variant="primary" href={kanbanHref}')
    expect(mainKanbanPanelSource).toContain('Open Kanban')
    expect(mainKanbanPanelSource).toContain("import { Popover } from 'bits-ui'")
    expect(mainKanbanPanelSource).toContain('getKanbanBoard')
    expect(mainKanbanPanelSource).toContain('listKanbanBoards')
    expect(mainKanbanPanelSource).toContain('kanbanCurrentBoardLabel')
    expect(mainKanbanPanelSource).toContain('BOARD::{kanbanCurrentBoardLabel}')
    expect(mainKanbanPanelSource).toContain(
      '<Button {...props} size="sm" chrome="ghost" variant="primary">BOARD::{kanbanCurrentBoardLabel}</Button>'
    )
    expect(mainKanbanPanelSource).toContain('available boards')
    expect(mainKanbanPanelSource).toContain('selectKanbanBoard')
    expect(mainKanbanPanelSource).toContain('onclick={() => void selectKanbanBoard(board)}')
    expect(mainKanbanPanelSource).toContain("variant={board.slug === kanbanCurrentBoardSlug ? 'primary' : 'default'}")
    expect(mainKanbanPanelSource).toContain('resolveKanbanBoardSlug')
    expect(mainKanbanPanelSource).toContain('Focus queue')
    expect(mainKanbanPanelSource).toContain('kanbanFocusTasks')
    expect(mainKanbanPanelSource).toContain("{ label: 'Active'")
    expect(mainKanbanPanelSource).toContain("{ label: 'Running'")
    expect(mainKanbanPanelSource).toContain("{ label: 'Ready'")
    expect(mainKanbanPanelSource).toContain("{ label: 'Blocked'")
    expect(mainKanbanPanelSource).not.toContain("{ label: 'Board'")
    expect(mainKanbanPanelSource).not.toContain('kanbanBoardTriggerClass')
    expect(mainKanbanPanelSource).not.toContain('kanbanBoardItemClass')
    expect(mainKanbanPanelSource).not.toContain('Kanban route is wired through the authenticated dashboard plugin API.')
    expect(dashboardSource).toContain("id: 'calendar'")
    expect(dashboardSource).toContain('href: `#${calendarRoute()}`')
    expect(dashboardSource).toContain("id: 'cron'")
    expect(dashboardSource).toContain('href: `#${cronRoute()}`')
    expect(dashboardSource).toContain("id: 'kanban'")
    expect(dashboardSource).toContain('href: `#${kanbanRoute()}`')
    expect(dashboardSource).not.toContain("state: 'planned'")
  })
})
